# frozen_string_literal: true

require 'active_support/all'
require 'ffaker'
require 'psgc'

# Generate a random set of digits not starting with zero
def random_not_starting_with_zero(digits)
  max = 10**digits
  min = 10**(digits - 1)
  Random.rand(min...max).to_s
end

# Typeface name and normalised pt size
FONTS = {
  'Bartdeng Regular' => 20
}.freeze

# # PSGC data
# PROVINCES = PSGC::Region.all.map(&:provinces).flatten

# # Monkey patch PSGC::ProvinceOrDistrict to add a random city or municipality picker
# module PSGC
#   # PSGC::ProvinceOrDistrict
#   class ProvinceOrDistrict
#     def cities_or_municipalities
#       @cities_or_municipalities ||= (cities + municipalities)
#     end

#     def random_city_or_municipality
#       cities_or_municipalities.sample
#     end
#   end
# end

# Used for place of birth, and as a superclass for Address
class CountryProvinceMunicipality
  attr_accessor :country, :province_or_state, :city_or_municipality

  def self.random
    CountryProvinceMunicipality.new.tap do |cpm|
      cpm.country = 'PH'
      province = ImpProvinces.sample[:code]
      cpm.province_or_state = province
      city = ImpCities.select { |city| city[:province] == province }
      cpm.city_or_municipality = city.sample[:name]
      # cpm.country = 'Philippines'
      # province = PROVINCES.sample
      # cpm.province_or_state = province.name.tr("',","").capitalize
      # cpm.city_or_municipality = province.random_city_or_municipality.name.tr("',","").capitalize
    end
  end
end

# An address
class Address < CountryProvinceMunicipality
  attr_accessor :line_1, :line_2, :zip_code

  def self.random_zip_code
    Random.rand(1000..9999).to_s
  end

  def self.random
    Address.new.tap do |address|
      address.country = 'PH'
      province = ImpProvinces.sample[:code]
      address.province_or_state = province
      city = ImpCities.select { |city| city[:province] == province }
      address.city_or_municipality = city.sample[:name]
      # address.country = 'Philippines'
      # province = PROVINCES.sample
      # address.province_or_state = province.name.tr("',","").capitalize
      # address.city_or_municipality = province.random_city_or_municipality.name.tr("',","").capitalize
      address.line_1 = FFaker::Address.street_address.tr("',","")
      address.line_2 = FFaker::Address.neighborhood.tr("',","")
      address.zip_code = random_zip_code
    end
  end
end

# A struct to hold PH government ID data
class GovernmentId
  attr_accessor :type, :number
  # Date
  attr_accessor :valid_until
  attr_accessor :image_file

  # Also allows
  TYPES = ['id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06', 'id-07', 'id-08', 'id-09', 'id-10', 'id-11', 'id-12'].freeze

  # Generates a random government TIN, GSIS, SSS or CRN
  def self.random_tin_gsis_sss_or_crn
    GovernmentId.new.tap do |id|
      id.type = TYPES.sample
      id.number = case id.type
                  when 'id-03'
                    random_not_starting_with_zero(10)
                  when 'id-12'
                    random_not_starting_with_zero(11)
                  when 'id-05'
                    random_not_starting_with_zero(9)
                  else 
                    random_not_starting_with_zero(12)
                  end
      id.valid_until = FFaker::Time.between(1.year.from_now, 10.years.from_now).to_date.strftime('%b/%d/%Y')
      id.image_file = 'images/' + Random.rand(18).to_s + '.jpeg'
    end
  end
end

# A Filipino
# rubocop:disable Metrics/ClassLength
class Person
  # rubocop:enable Metrics/ClassLength
  attr_accessor :first_name, :middle_name, :last_name, :suffix
  attr_accessor :nationality

  # Date
  attr_accessor :birth_date

  # 'male' | 'female'
  attr_accessor :sex

  # CountryProvinceMunicipality
  attr_accessor :place_of_birth

  # Address
  attr_accessor :permanent_address, :present_address

  attr_accessor :mobile_number
  attr_accessor :landline
  attr_accessor :email
  attr_accessor :nature_of_work, :source_of_funds, :industry, :name_of_employer
  attr_accessor :tin, :sss, :gsis, :crn
  attr_accessor :photograph 
  attr_accessor :specimen_signature
  attr_accessor :government_id1
  attr_accessor :government_id2

  def full_name
    [first_name, middle_name, last_name, suffix].reject(&:blank?).join(' ')
  end

  NATURE_OF_WORK = {
    'employed' => 30,
    'business' => 25,
    'unemployed' => 5,
    'retired' => 5,
    'homemaker' => 5,
    'student' => 10,
    'ofw' => 20
  }.freeze

  SOURCE_OF_FUNDS = {
    'employed' => 'salary',
    'business' => 'income-business',
    'unemployed' => 'remittances',
    'retired' => 'remittances',
    'homemaker' => 'remittances',
    'student' => 'support-relatives',
    'ofw' => 'salary'
  }.freeze

  PSIC = <<~PSIC
    agriculture
    mining
    manufacturing
    electricity
    water
    construction
    trade
    transportation
    hrm
    it
    finance
    real-estate
    professional
    admin
    public
    education
    social
    arts
    domestic
  PSIC
         .lines.map { |s| s.chomp }

  class << self
    # Randomized according to
    # 30% Employed
    # 25% Business Owner/Freelancer
    # 5% unemployed
    # 10% Pensioner/Retired/homemaker
    # 10% student
    # 20% OFW
    def random_nature_of_work
      raw_nature_of_work.split('/').sample
    end

    private

    def raw_nature_of_work
      i = Random.rand(100)
      NATURE_OF_WORK.each do |k, w|
        return k if i < w

        i -= w
      end
    end

    def random_passport_number
      (Array.new(2).map { ('A'..'Z').to_a.sample } + Array.new(7).map { Random.rand(10) }).join
    end

    public

    def random_digits(digits, prefix = nil)
      ([prefix] + Array.new(digits).map { Random.rand(10) }).join
    end

    # Generate a Person record using pr
    # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/MethodLength, Metrics/PerceivedComplexity
    def generate
      # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/MethodLength, Metrics/PerceivedComplexity
      # rubocop:disable Metrics/BlockLength
      Person.new.tap do |p|
        # rubocop:enable Metrics/BlockLength
        male = Random.rand(2) == 1
        # 20% of the population will have a second name
        n_names = Random.rand(5).zero? ? 2 : 1
        p.first_name = Array.new(n_names).map do
          male ? FFaker::NamePH.first_name_male.tr("',","") : FFaker::NamePH.first_name_female
        end.join(' ').tr("',","")
        p.middle_name = FFaker::NamePH.last_name.tr("',","")
        p.last_name = FFaker::NamePH.last_name.tr("',","")
        # 5% of Male to have Sr. 5% of Male to have Jr.
        if male
          case Random.rand(20)
          when 0
            p.suffix = 'sr'
          when 1
            p.suffix = 'jr'
          when 2
            p.suffix = 'ii'
          when 3
            p.suffix = 'iii'
          when 4
            p.suffix = 'iv'
          end
        end
        p.sex = male ? 'm' : 'f'

        p.birth_date = FFaker::Time.between(70.years.ago, 18.years.ago).to_date.strftime('%b/%d/%Y')

        p.place_of_birth = CountryProvinceMunicipality.random

        p.permanent_address = Address.random
        # 33% will have a different present address from permanent address
        p.present_address = Random.rand(3).zero? ? Address.random : p.permanent_address

        # (+63) + "9" + randomize 9 random numbers
        p.mobile_number = '+639' + Array.new(9) { Random.rand(10) }.join + ''
        p.landline = Array.new(7) {Random.rand(10)}.join 
        p.email = rand(26**5).to_s(10) + '@gmail.com' 
        p.nationality = 'PH'

        p.nature_of_work = random_nature_of_work
        p.source_of_funds = SOURCE_OF_FUNDS[p.nature_of_work]
        if ['employed', 'business', 'ofw'].include?(p.nature_of_work)
          p.industry = PSIC.sample
          p.name_of_employer = FFaker::Company.name.tr("',","")
        end

        p.photograph = 'images/pic_' + Random.rand(9).to_s + '.jpeg'
        p.specimen_signature = 'images/sig_' + Random.rand(3).to_s + '.jpeg'

        # ONLY IF Nature of Work is NOT unemployed, Student or homemaker
        # then choose randomly between generating a TIN, GSIS, SSS, CRN
        unless %w[unemployed student homemaker].include?(p.nature_of_work)
          id1 = GovernmentId.random_tin_gsis_sss_or_crn
          case id1.type
          when 'id-03'
            p.sss = id1.number
          when 'id-12'
            p.gsis = id1.number
          when 'id-05'
            p.tin = id1.number
          else 
            p.crn = id1.number
          end
        end

        id2 = GovernmentId.random_tin_gsis_sss_or_crn
        case p.nature_of_work
        when 'homemaker'
          id2.type = 'id-01'
          id2.number = random_passport_number
        when 'student'
          id2.type = 'id-04'
          id2.number = random_not_starting_with_zero(10)
        end
        p.government_id1 = id1

        unless %w[unemployed student homemaker].include?(p.nature_of_work)
          id2 = GovernmentId.random_tin_gsis_sss_or_crn
          case id2.type
          when 'id-03'
            p.sss = id2.number
          when 'id-12'
            p.gsis = id2.number
          when 'id-05'
            p.tin = id2.number
          else 
            p.crn = id2.number
          end
        end 

        id2 = GovernmentId.random_tin_gsis_sss_or_crn
        case p.nature_of_work
        when 'homemaker'
          id2.type = 'id-01'
          id2.number = random_passport_number
        when 'student'
          id2.type = 'id-04'
          id2.number = random_not_starting_with_zero(10)
        end
        p.government_id2 = id2
      end
    end
  end
end

ImpProvinces = [
  { code: 'PH-00', name: 'Metro Manila', region: 'PH-00' },
  { code: 'PH-ILN', name: 'Ilocos Norte', region: 'PH-01' },
  { code: 'PH-ILS', name: 'Ilocos Sur', region: 'PH-01' },
  { code: 'PH-LUN', name: 'La Union', region: 'PH-01' },
  { code: 'PH-PAN', name: 'Pangasinan', region: 'PH-01' },
  { code: 'PH-BTN', name: 'Batanes', region: 'PH-02' },
  { code: 'PH-CAG', name: 'Cagayan', region: 'PH-02' },
  { code: 'PH-ISA', name: 'Isabela', region: 'PH-02' },
  { code: 'PH-NUV', name: 'Nueva Vizcaya', region: 'PH-02' },
  { code: 'PH-QUI', name: 'Quirino', region: 'PH-02' },
  { code: 'PH-AUR', name: 'Aurora', region: 'PH-03' },
  { code: 'PH-BAN', name: 'Bataan', region: 'PH-03' },
  { code: 'PH-BUL', name: 'Bulacan', region: 'PH-03' },
  { code: 'PH-NUE', name: 'Nueva Ecija', region: 'PH-03' },
  { code: 'PH-PAM', name: 'Pampanga', region: 'PH-03' },
  { code: 'PH-TAR', name: 'Tarlac', region: 'PH-03' },
  { code: 'PH-ZMB', name: 'Zambales', region: 'PH-03' },
  { code: 'PH-ALB', name: 'Albay', region: 'PH-05' },
  { code: 'PH-CAN', name: 'Camarines Norte', region: 'PH-05' },
  { code: 'PH-CAS', name: 'Camarines Sur', region: 'PH-05' },
  { code: 'PH-CAT', name: 'Catanduanes', region: 'PH-05' },
  { code: 'PH-MAS', name: 'Masbate', region: 'PH-05' },
  { code: 'PH-SOR', name: 'Sorsogon', region: 'PH-05' },
  { code: 'PH-AKL', name: 'Aklan', region: 'PH-06' },
  { code: 'PH-ANT', name: 'Antique', region: 'PH-06' },
  { code: 'PH-CAP', name: 'Capiz', region: 'PH-06' },
  { code: 'PH-GUI', name: 'Guimaras', region: 'PH-06' },
  { code: 'PH-ILI', name: 'Iloilo', region: 'PH-06' },
  { code: 'PH-NEC', name: 'Negros Occidental', region: 'PH-06' },
  { code: 'PH-BOH', name: 'Bohol', region: 'PH-07' },
  { code: 'PH-CEB', name: 'Cebu', region: 'PH-07' },
  { code: 'PH-NER', name: 'Negros Oriental', region: 'PH-07' },
  { code: 'PH-SIG', name: 'Siquijor', region: 'PH-07' },
  { code: 'PH-BIL', name: 'Biliran', region: 'PH-08' },
  { code: 'PH-EAS', name: 'Eastern Samar', region: 'PH-08' },
  { code: 'PH-LEY', name: 'Leyte', region: 'PH-08' },
  { code: 'PH-NSA', name: 'Northern Samar', region: 'PH-08' },
  { code: 'PH-WSA', name: 'Samar (Western Samar)', region: 'PH-08' },
  { code: 'PH-SLE', name: 'Southern Leyte', region: 'PH-08' },
  { code: 'PH-BAS', name: 'Basilan ', region: 'PH-09' },
  { code: 'PH-ZAN', name: 'Zamboanga del Norte', region: 'PH-09' },
  { code: 'PH-ZAS', name: 'Zamboanga del Sur', region: 'PH-09' },
  { code: 'PH-ZSI', name: 'Zamboanga Sibugay', region: 'PH-09' },
  { code: 'PH-BUK', name: 'Bukidnon', region: 'PH-10' },
  { code: 'PH-CAM', name: 'Camiguin', region: 'PH-10' },
  { code: 'PH-MSC', name: 'Misamis Occidental', region: 'PH-10' },
  { code: 'PH-MSR', name: 'Misamis Oriental', region: 'PH-10' },
  { code: 'PH-COM', name: 'Compostela Valley', region: 'PH-11' },
  { code: 'PH-DAV', name: 'Davao del Norte', region: 'PH-11' },
  { code: 'PH-DAS', name: 'Davao del Sur', region: 'PH-11' },
  { code: 'PH-DVO', name: 'Davao Occidental', region: 'PH-11' },
  { code: 'PH-DAO', name: 'Davao Oriental', region: 'PH-11' },
  { code: 'PH-SAR', name: 'Sarangani ', region: 'PH-11' },
  { code: 'PH-SCO', name: 'South Cotabato ', region: 'PH-11' },
  { code: 'PH-NCO', name: 'Cotabato', region: 'PH-12' },
  { code: 'PH-LAN', name: 'Lanao del Norte ', region: 'PH-12' },
  { code: 'PH-SUK', name: 'Sultan Kudarat', region: 'PH-12' },
  { code: 'PH-AGN', name: 'Agusan del Norte', region: 'PH-13' },
  { code: 'PH-AGS', name: 'Agusan del Sur', region: 'PH-13' },
  { code: 'PH-DIN', name: 'Dinagat Islands', region: 'PH-13' },
  { code: 'PH-SUN', name: 'Surigao del Norte', region: 'PH-13' },
  { code: 'PH-SUR', name: 'Surigao del Sur', region: 'PH-13' },
  { code: 'PH-LAS', name: 'Lanao del Sur', region: 'PH-14' },
  { code: 'PH-MAG', name: 'Maguindanao', region: 'PH-14' },
  { code: 'PH-SLU', name: 'Sulu', region: 'PH-14' },
  { code: 'PH-TAW', name: 'Tawi-Tawi', region: 'PH-14' },
  { code: 'PH-ABR', name: 'Abra', region: 'PH-15' },
  { code: 'PH-APA', name: 'Apayao', region: 'PH-15' },
  { code: 'PH-BEN', name: 'Benguet', region: 'PH-15' },
  { code: 'PH-IFU', name: 'Ifugao', region: 'PH-15' },
  { code: 'PH-KAL', name: 'Kalinga', region: 'PH-15' },
  { code: 'PH-MOU', name: 'Mountain Province', region: 'PH-15' },
  { code: 'PH-BTG', name: 'Batangas', region: 'PH-40' },
  { code: 'PH-CAV', name: 'Cavite', region: 'PH-40' },
  { code: 'PH-LAG', name: 'Laguna', region: 'PH-40' },
  { code: 'PH-QUE', name: 'Quezon', region: 'PH-40' },
  { code: 'PH-RIZ', name: 'Rizal', region: 'PH-40' },
  { code: 'PH-MAD', name: 'Marinduque', region: 'PH-41' },
  { code: 'PH-MDC', name: 'Occidental Mindoro', region: 'PH-41' },
  { code: 'PH-MDR', name: 'Oriental Mindoro', region: 'PH-41' },
  { code: 'PH-PLW', name: 'Palawan', region: 'PH-41' },
  { code: 'PH-ROM', name: 'Romblon', region: 'PH-41' },
]

ImpCities = [
  { name: 'Bangued', province: 'PH-ABR' },
  { name: 'Boliney', province: 'PH-ABR' },
  { name: 'Bucay', province: 'PH-ABR' },
  { name: 'Bucloc', province: 'PH-ABR' },
  { name: 'Daguioman', province: 'PH-ABR' },
  { name: 'Danglas', province: 'PH-ABR' },
  { name: 'Dolores', province: 'PH-ABR' },
  { name: 'La Paz', province: 'PH-ABR' },
  { name: 'Lacub', province: 'PH-ABR' },
  { name: 'Lagangilang', province: 'PH-ABR' },
  { name: 'Lagayan', province: 'PH-ABR' },
  { name: 'Langiden', province: 'PH-ABR' },
  { name: 'Licuan-Baay (Licuan)', province: 'PH-ABR' },
  { name: 'Luba', province: 'PH-ABR' },
  { name: 'Malibcong', province: 'PH-ABR' },
  { name: 'Manabo', province: 'PH-ABR' },
  { name: 'Peñarrubia', province: 'PH-ABR' },
  { name: 'Pidigan', province: 'PH-ABR' },
  { name: 'Pilar', province: 'PH-ABR' },
  { name: 'Sallapadan', province: 'PH-ABR' },
  { name: 'San Isidro', province: 'PH-ABR' },
  { name: 'San Juan', province: 'PH-ABR' },
  { name: 'San Quintin', province: 'PH-ABR' },
  { name: 'Tayum', province: 'PH-ABR' },
  { name: 'Tineg', province: 'PH-ABR' },
  { name: 'Tubo', province: 'PH-ABR' },
  { name: 'Villaviciosa', province: 'PH-ABR' },
  { name: 'Buenavista', province: 'PH-AGN' },
  { name: 'Butuan', province: 'PH-AGN' },
  { name: 'Cabadbaran', province: 'PH-AGN' },
  { name: 'Carmen', province: 'PH-AGN' },
  { name: 'Jabonga', province: 'PH-AGN' },
  { name: 'Kitcharao', province: 'PH-AGN' },
  { name: 'Las Nieves', province: 'PH-AGN' },
  { name: 'Magallanes', province: 'PH-AGN' },
  { name: 'Nasipit', province: 'PH-AGN' },
  { name: 'Remedios T. Romualdez', province: 'PH-AGN' },
  { name: 'Santiago', province: 'PH-AGN' },
  { name: 'Tubay', province: 'PH-AGN' },
  { name: 'Bayugan', province: 'PH-AGS' },
  { name: 'Bunawan', province: 'PH-AGS' },
  { name: 'Esperanza', province: 'PH-AGS' },
  { name: 'La Paz', province: 'PH-AGS' },
  { name: 'Loreto', province: 'PH-AGS' },
  { name: 'Prosperidad', province: 'PH-AGS' },
  { name: 'Rosario', province: 'PH-AGS' },
  { name: 'San Francisco', province: 'PH-AGS' },
  { name: 'San Luis', province: 'PH-AGS' },
  { name: 'Santa Josefa', province: 'PH-AGS' },
  { name: 'Sibagat', province: 'PH-AGS' },
  { name: 'Talacogon', province: 'PH-AGS' },
  { name: 'Trento', province: 'PH-AGS' },
  { name: 'Veruela', province: 'PH-AGS' },
  { name: 'Altavas', province: 'PH-AKL' },
  { name: 'Balete', province: 'PH-AKL' },
  { name: 'Banga', province: 'PH-AKL' },
  { name: 'Batan', province: 'PH-AKL' },
  { name: 'Buruanga', province: 'PH-AKL' },
  { name: 'Ibajay', province: 'PH-AKL' },
  { name: 'Kalibo', province: 'PH-AKL' },
  { name: 'Lezo', province: 'PH-AKL' },
  { name: 'Libacao', province: 'PH-AKL' },
  { name: 'Madalag', province: 'PH-AKL' },
  { name: 'Makato', province: 'PH-AKL' },
  { name: 'Malay', province: 'PH-AKL' },
  { name: 'Malinao', province: 'PH-AKL' },
  { name: 'Nabas', province: 'PH-AKL' },
  { name: 'New Washington', province: 'PH-AKL' },
  { name: 'Numancia', province: 'PH-AKL' },
  { name: 'Tangalan', province: 'PH-AKL' },
  { name: 'Bacacay', province: 'PH-ALB' },
  { name: 'Camalig', province: 'PH-ALB' },
  { name: 'Daraga (Locsin)', province: 'PH-ALB' },
  { name: 'Guinobatan', province: 'PH-ALB' },
  { name: 'Jovellar', province: 'PH-ALB' },
  { name: 'Legazpi', province: 'PH-ALB' },
  { name: 'Libon', province: 'PH-ALB' },
  { name: 'Ligao', province: 'PH-ALB' },
  { name: 'Malilipot', province: 'PH-ALB' },
  { name: 'Malinao', province: 'PH-ALB' },
  { name: 'Manito', province: 'PH-ALB' },
  { name: 'Oas', province: 'PH-ALB' },
  { name: 'Pio Duran', province: 'PH-ALB' },
  { name: 'Polangui', province: 'PH-ALB' },
  { name: 'Rapu-Rapu', province: 'PH-ALB' },
  { name: 'Santo Domingo (Libog)', province: 'PH-ALB' },
  { name: 'Tabaco', province: 'PH-ALB' },
  { name: 'Tiwi', province: 'PH-ALB' },
  { name: 'Anini-y', province: 'PH-ANT' },
  { name: 'Barbaza', province: 'PH-ANT' },
  { name: 'Belison', province: 'PH-ANT' },
  { name: 'Bugasong', province: 'PH-ANT' },
  { name: 'Caluya', province: 'PH-ANT' },
  { name: 'Culasi', province: 'PH-ANT' },
  { name: 'Hamtic', province: 'PH-ANT' },
  { name: 'Laua-an', province: 'PH-ANT' },
  { name: 'Libertad', province: 'PH-ANT' },
  { name: 'Pandan', province: 'PH-ANT' },
  { name: 'Patnongon', province: 'PH-ANT' },
  { name: 'San Jose de Buenavista', province: 'PH-ANT' },
  { name: 'San Remigio', province: 'PH-ANT' },
  { name: 'Sebaste', province: 'PH-ANT' },
  { name: 'Sibalom', province: 'PH-ANT' },
  { name: 'Tibiao', province: 'PH-ANT' },
  { name: 'Tobias Fornier (Dao)', province: 'PH-ANT' },
  { name: 'Valderrama', province: 'PH-ANT' },
  { name: 'Calanasan (Bayag)', province: 'PH-APA' },
  { name: 'Conner', province: 'PH-APA' },
  { name: 'Flora', province: 'PH-APA' },
  { name: 'Kabugao', province: 'PH-APA' },
  { name: 'Luna', province: 'PH-APA' },
  { name: 'Pudtol', province: 'PH-APA' },
  { name: 'Santa Marcela', province: 'PH-APA' },
  { name: 'Baler', province: 'PH-AUR' },
  { name: 'Casiguran', province: 'PH-AUR' },
  { name: 'Dilasag', province: 'PH-AUR' },
  { name: 'Dinalungan', province: 'PH-AUR' },
  { name: 'Dingalan', province: 'PH-AUR' },
  { name: 'Dipaculao', province: 'PH-AUR' },
  { name: 'Maria Aurora', province: 'PH-AUR' },
  { name: 'San Luis', province: 'PH-AUR' },
  { name: 'Akbar', province: 'PH-BAS' },
  { name: 'Al-Barka', province: 'PH-BAS' },
  { name: 'Hadji Mohammad Ajul', province: 'PH-BAS' },
  { name: 'Hadji Muhtamad', province: 'PH-BAS' },
  { name: 'Isabela City', province: 'PH-BAS' },
  { name: 'Lamitan', province: 'PH-BAS' },
  { name: 'Lantawan', province: 'PH-BAS' },
  { name: 'Maluso', province: 'PH-BAS' },
  { name: 'Sumisip', province: 'PH-BAS' },
  { name: 'Tabuan-Lasa', province: 'PH-BAS' },
  { name: 'Tipo-Tipo', province: 'PH-BAS' },
  { name: 'Tuburan', province: 'PH-BAS' },
  { name: 'Ungkaya Pukan', province: 'PH-BAS' },
  { name: 'Abucay', province: 'PH-BAN' },
  { name: 'Bagac', province: 'PH-BAN' },
  { name: 'Balanga', province: 'PH-BAN' },
  { name: 'Dinalupihan', province: 'PH-BAN' },
  { name: 'Hermosa', province: 'PH-BAN' },
  { name: 'Limay', province: 'PH-BAN' },
  { name: 'Mariveles', province: 'PH-BAN' },
  { name: 'Morong', province: 'PH-BAN' },
  { name: 'Orani', province: 'PH-BAN' },
  { name: 'Orion', province: 'PH-BAN' },
  { name: 'Pilar', province: 'PH-BAN' },
  { name: 'Samal', province: 'PH-BAN' },
  { name: 'Basco', province: 'PH-BTN' },
  { name: 'Itbayat', province: 'PH-BTN' },
  { name: 'Ivana', province: 'PH-BTN' },
  { name: 'Mahatao', province: 'PH-BTN' },
  { name: 'Sabtang', province: 'PH-BTN' },
  { name: 'Uyugan', province: 'PH-BTN' },
  { name: 'Agoncillo', province: 'PH-BTG' },
  { name: 'Alitagtag', province: 'PH-BTG' },
  { name: 'Balayan', province: 'PH-BTG' },
  { name: 'Balete', province: 'PH-BTG' },
  { name: 'Batangas City', province: 'PH-BTG' },
  { name: 'Bauan', province: 'PH-BTG' },
  { name: 'Calaca', province: 'PH-BTG' },
  { name: 'Calatagan', province: 'PH-BTG' },
  { name: 'Cuenca', province: 'PH-BTG' },
  { name: 'Ibaan', province: 'PH-BTG' },
  { name: 'Laurel', province: 'PH-BTG' },
  { name: 'Lemery', province: 'PH-BTG' },
  { name: 'Lian', province: 'PH-BTG' },
  { name: 'Lipa', province: 'PH-BTG' },
  { name: 'Lobo', province: 'PH-BTG' },
  { name: 'Mabini', province: 'PH-BTG' },
  { name: 'Malvar', province: 'PH-BTG' },
  { name: 'Mataasnakahoy', province: 'PH-BTG' },
  { name: 'Nasugbu', province: 'PH-BTG' },
  { name: 'Padre Garcia', province: 'PH-BTG' },
  { name: 'Rosario', province: 'PH-BTG' },
  { name: 'San Jose', province: 'PH-BTG' },
  { name: 'San Juan', province: 'PH-BTG' },
  { name: 'San Luis', province: 'PH-BTG' },
  { name: 'San Nicolas', province: 'PH-BTG' },
  { name: 'San Pascual', province: 'PH-BTG' },
  { name: 'Santa Teresita', province: 'PH-BTG' },
  { name: 'Santo Tomas', province: 'PH-BTG' },
  { name: 'Taal', province: 'PH-BTG' },
  { name: 'Talisay', province: 'PH-BTG' },
  { name: 'Tanauan', province: 'PH-BTG' },
  { name: 'Taysan', province: 'PH-BTG' },
  { name: 'Tingloy', province: 'PH-BTG' },
  { name: 'Tuy', province: 'PH-BTG' },
  { name: 'Atok', province: 'PH-BEN' },
  { name: 'Baguio', province: 'PH-BEN' },
  { name: 'Bakun', province: 'PH-BEN' },
  { name: 'Bokod', province: 'PH-BEN' },
  { name: 'Buguias', province: 'PH-BEN' },
  { name: 'Itogon', province: 'PH-BEN' },
  { name: 'Kabayan', province: 'PH-BEN' },
  { name: 'Kapangan', province: 'PH-BEN' },
  { name: 'Kibungan', province: 'PH-BEN' },
  { name: 'La Trinidad', province: 'PH-BEN' },
  { name: 'Mankayan', province: 'PH-BEN' },
  { name: 'Sablan', province: 'PH-BEN' },
  { name: 'Tuba', province: 'PH-BEN' },
  { name: 'Tublay', province: 'PH-BEN' },
  { name: 'Almeria', province: 'PH-BIL' },
  { name: 'Biliran', province: 'PH-BIL' },
  { name: 'Cabucgayan', province: 'PH-BIL' },
  { name: 'Caibiran', province: 'PH-BIL' },
  { name: 'Culaba', province: 'PH-BIL' },
  { name: 'Kawayan', province: 'PH-BIL' },
  { name: 'Maripipi', province: 'PH-BIL' },
  { name: 'Naval', province: 'PH-BIL' },
  { name: 'Alburquerque', province: 'PH-BOH' },
  { name: 'Alicia', province: 'PH-BOH' },
  { name: 'Anda', province: 'PH-BOH' },
  { name: 'Antequera', province: 'PH-BOH' },
  { name: 'Baclayon', province: 'PH-BOH' },
  { name: 'Balilihan', province: 'PH-BOH' },
  { name: 'Batuan', province: 'PH-BOH' },
  { name: 'Bien Unido', province: 'PH-BOH' },
  { name: 'Bilar', province: 'PH-BOH' },
  { name: 'Buenavista', province: 'PH-BOH' },
  { name: 'Calape', province: 'PH-BOH' },
  { name: 'Candijay', province: 'PH-BOH' },
  { name: 'Carmen', province: 'PH-BOH' },
  { name: 'Catigbian', province: 'PH-BOH' },
  { name: 'Clarin', province: 'PH-BOH' },
  { name: 'Corella', province: 'PH-BOH' },
  { name: 'Cortes', province: 'PH-BOH' },
  { name: 'Dagohoy', province: 'PH-BOH' },
  { name: 'Danao', province: 'PH-BOH' },
  { name: 'Dauis', province: 'PH-BOH' },
  { name: 'Dimiao', province: 'PH-BOH' },
  { name: 'Duero', province: 'PH-BOH' },
  { name: 'Garcia Hernandez', province: 'PH-BOH' },
  { name: 'Getafe', province: 'PH-BOH' },
  { name: 'Guindulman', province: 'PH-BOH' },
  { name: 'Inabanga', province: 'PH-BOH' },
  { name: 'Jagna', province: 'PH-BOH' },
  { name: 'Lila', province: 'PH-BOH' },
  { name: 'Loay', province: 'PH-BOH' },
  { name: 'Loboc', province: 'PH-BOH' },
  { name: 'Loon', province: 'PH-BOH' },
  { name: 'Mabini', province: 'PH-BOH' },
  { name: 'Maribojoc', province: 'PH-BOH' },
  { name: 'Panglao', province: 'PH-BOH' },
  { name: 'Pilar', province: 'PH-BOH' },
  { name: 'President Carlos P. Garcia (Pitogo)', province: 'PH-BOH' },
  { name: 'Sagbayan (Borja)', province: 'PH-BOH' },
  { name: 'San Isidro', province: 'PH-BOH' },
  { name: 'San Miguel', province: 'PH-BOH' },
  { name: 'Sevilla', province: 'PH-BOH' },
  { name: 'Sierra Bullones', province: 'PH-BOH' },
  { name: 'Sikatuna', province: 'PH-BOH' },
  { name: 'Tagbilaran', province: 'PH-BOH' },
  { name: 'Talibon', province: 'PH-BOH' },
  { name: 'Trinidad', province: 'PH-BOH' },
  { name: 'Tubigon', province: 'PH-BOH' },
  { name: 'Ubay', province: 'PH-BOH' },
  { name: 'Valencia', province: 'PH-BOH' },
  { name: 'Baungon', province: 'PH-BUK' },
  { name: 'Cabanglasan', province: 'PH-BUK' },
  { name: 'Damulog', province: 'PH-BUK' },
  { name: 'Dangcagan', province: 'PH-BUK' },
  { name: 'Don Carlos', province: 'PH-BUK' },
  { name: 'Impasugong', province: 'PH-BUK' },
  { name: 'Kadingilan', province: 'PH-BUK' },
  { name: 'Kalilangan', province: 'PH-BUK' },
  { name: 'Kibawe', province: 'PH-BUK' },
  { name: 'Kitaotao', province: 'PH-BUK' },
  { name: 'Lantapan', province: 'PH-BUK' },
  { name: 'Libona', province: 'PH-BUK' },
  { name: 'Malaybalay', province: 'PH-BUK' },
  { name: 'Malitbog', province: 'PH-BUK' },
  { name: 'Manolo Fortich', province: 'PH-BUK' },
  { name: 'Maramag', province: 'PH-BUK' },
  { name: 'Pangantucan', province: 'PH-BUK' },
  { name: 'Quezon', province: 'PH-BUK' },
  { name: 'San Fernando', province: 'PH-BUK' },
  { name: 'Sumilao', province: 'PH-BUK' },
  { name: 'Talakag', province: 'PH-BUK' },
  { name: 'Valencia', province: 'PH-BUK' },
  { name: 'Angat', province: 'PH-BUL' },
  { name: 'Balagtas (Bigaa)', province: 'PH-BUL' },
  { name: 'Baliuag', province: 'PH-BUL' },
  { name: 'Bocaue', province: 'PH-BUL' },
  { name: 'Bulakan', province: 'PH-BUL' },
  { name: 'Bustos', province: 'PH-BUL' },
  { name: 'Calumpit', province: 'PH-BUL' },
  { name: 'Doña Remedios Trinidad', province: 'PH-BUL' },
  { name: 'Guiguinto', province: 'PH-BUL' },
  { name: 'Hagonoy', province: 'PH-BUL' },
  { name: 'Malolos', province: 'PH-BUL' },
  { name: 'Marilao', province: 'PH-BUL' },
  { name: 'Meycauayan', province: 'PH-BUL' },
  { name: 'Norzagaray', province: 'PH-BUL' },
  { name: 'Obando', province: 'PH-BUL' },
  { name: 'Pandi', province: 'PH-BUL' },
  { name: 'Paombong', province: 'PH-BUL' },
  { name: 'Plaridel', province: 'PH-BUL' },
  { name: 'Pulilan', province: 'PH-BUL' },
  { name: 'San Ildefonso', province: 'PH-BUL' },
  { name: 'San Jose del Monte', province: 'PH-BUL' },
  { name: 'San Miguel', province: 'PH-BUL' },
  { name: 'San Rafael', province: 'PH-BUL' },
  { name: 'Santa Maria', province: 'PH-BUL' },
  { name: 'Abulug', province: 'PH-CAG' },
  { name: 'Alcala', province: 'PH-CAG' },
  { name: 'Allacapan', province: 'PH-CAG' },
  { name: 'Amulung', province: 'PH-CAG' },
  { name: 'Aparri', province: 'PH-CAG' },
  { name: 'Baggao', province: 'PH-CAG' },
  { name: 'Ballesteros', province: 'PH-CAG' },
  { name: 'Buguey', province: 'PH-CAG' },
  { name: 'Calayan', province: 'PH-CAG' },
  { name: 'Camalaniugan', province: 'PH-CAG' },
  { name: 'Claveria', province: 'PH-CAG' },
  { name: 'Enrile', province: 'PH-CAG' },
  { name: 'Gattaran', province: 'PH-CAG' },
  { name: 'Gonzaga', province: 'PH-CAG' },
  { name: 'Iguig', province: 'PH-CAG' },
  { name: 'Lal-lo', province: 'PH-CAG' },
  { name: 'Lasam', province: 'PH-CAG' },
  { name: 'Pamplona', province: 'PH-CAG' },
  { name: 'Peñablanca', province: 'PH-CAG' },
  { name: 'Piat', province: 'PH-CAG' },
  { name: 'Rizal', province: 'PH-CAG' },
  { name: 'Sanchez-Mira', province: 'PH-CAG' },
  { name: 'Santa Ana', province: 'PH-CAG' },
  { name: 'Santa Praxedes', province: 'PH-CAG' },
  { name: 'Santa Teresita', province: 'PH-CAG' },
  { name: 'Santo Niño (Faire)', province: 'PH-CAG' },
  { name: 'Solana', province: 'PH-CAG' },
  { name: 'Tuao', province: 'PH-CAG' },
  { name: 'Tuguegarao', province: 'PH-CAG' },
  { name: 'Basud', province: 'PH-CAN' },
  { name: 'Capalonga', province: 'PH-CAN' },
  { name: 'Daet', province: 'PH-CAN' },
  { name: 'Jose Panganiban', province: 'PH-CAN' },
  { name: 'Labo', province: 'PH-CAN' },
  { name: 'Mercedes', province: 'PH-CAN' },
  { name: 'Paracale', province: 'PH-CAN' },
  { name: 'San Lorenzo Ruiz (Imelda)', province: 'PH-CAN' },
  { name: 'San Vicente', province: 'PH-CAN' },
  { name: 'Santa Elena', province: 'PH-CAN' },
  { name: 'Talisay', province: 'PH-CAN' },
  { name: 'Vinzons', province: 'PH-CAN' },
  { name: 'Baao', province: 'PH-CAS' },
  { name: 'Balatan', province: 'PH-CAS' },
  { name: 'Bato', province: 'PH-CAS' },
  { name: 'Bombon', province: 'PH-CAS' },
  { name: 'Buhi', province: 'PH-CAS' },
  { name: 'Bula', province: 'PH-CAS' },
  { name: 'Cabusao', province: 'PH-CAS' },
  { name: 'Calabanga', province: 'PH-CAS' },
  { name: 'Camaligan', province: 'PH-CAS' },
  { name: 'Canaman', province: 'PH-CAS' },
  { name: 'Caramoan', province: 'PH-CAS' },
  { name: 'Del Gallego', province: 'PH-CAS' },
  { name: 'Gainza', province: 'PH-CAS' },
  { name: 'Garchitorena', province: 'PH-CAS' },
  { name: 'Goa', province: 'PH-CAS' },
  { name: 'Iriga', province: 'PH-CAS' },
  { name: 'Lagonoy', province: 'PH-CAS' },
  { name: 'Libmanan', province: 'PH-CAS' },
  { name: 'Lupi', province: 'PH-CAS' },
  { name: 'Magarao', province: 'PH-CAS' },
  { name: 'Milaor', province: 'PH-CAS' },
  { name: 'Minalabac', province: 'PH-CAS' },
  { name: 'Nabua', province: 'PH-CAS' },
  { name: 'Naga', province: 'PH-CAS' },
  { name: 'Ocampo', province: 'PH-CAS' },
  { name: 'Pamplona', province: 'PH-CAS' },
  { name: 'Pasacao', province: 'PH-CAS' },
  { name: 'Pili', province: 'PH-CAS' },
  { name: 'Presentacion (Parubcan)', province: 'PH-CAS' },
  { name: 'Ragay', province: 'PH-CAS' },
  { name: 'Sagñay', province: 'PH-CAS' },
  { name: 'San Fernando', province: 'PH-CAS' },
  { name: 'San Jose', province: 'PH-CAS' },
  { name: 'Sipocot', province: 'PH-CAS' },
  { name: 'Siruma', province: 'PH-CAS' },
  { name: 'Tigaon', province: 'PH-CAS' },
  { name: 'Tinambac', province: 'PH-CAS' },
  { name: 'Catarman', province: 'PH-CAM' },
  { name: 'Guinsiliban', province: 'PH-CAM' },
  { name: 'Mahinog', province: 'PH-CAM' },
  { name: 'Mambajao', province: 'PH-CAM' },
  { name: 'Sagay', province: 'PH-CAM' },
  { name: 'Cuartero', province: 'PH-CAP' },
  { name: 'Dao', province: 'PH-CAP' },
  { name: 'Dumalag', province: 'PH-CAP' },
  { name: 'Dumarao', province: 'PH-CAP' },
  { name: 'Ivisan', province: 'PH-CAP' },
  { name: 'Jamindan', province: 'PH-CAP' },
  { name: 'Maayon', province: 'PH-CAP' },
  { name: 'Mambusao', province: 'PH-CAP' },
  { name: 'Panay', province: 'PH-CAP' },
  { name: 'Panitan', province: 'PH-CAP' },
  { name: 'Pilar', province: 'PH-CAP' },
  { name: 'Pontevedra', province: 'PH-CAP' },
  { name: 'President Roxas', province: 'PH-CAP' },
  { name: 'Roxas City', province: 'PH-CAP' },
  { name: 'Sapian', province: 'PH-CAP' },
  { name: 'Sigma', province: 'PH-CAP' },
  { name: 'Tapaz', province: 'PH-CAP' },
  { name: 'Bagamanoc', province: 'PH-CAT' },
  { name: 'Baras', province: 'PH-CAT' },
  { name: 'Bato', province: 'PH-CAT' },
  { name: 'Caramoran', province: 'PH-CAT' },
  { name: 'Gigmoto', province: 'PH-CAT' },
  { name: 'Pandan', province: 'PH-CAT' },
  { name: 'Panganiban (Payo)', province: 'PH-CAT' },
  { name: 'San Andres (Calolbon)', province: 'PH-CAT' },
  { name: 'San Miguel', province: 'PH-CAT' },
  { name: 'Viga', province: 'PH-CAT' },
  { name: 'Virac', province: 'PH-CAT' },
  { name: 'Alfonso', province: 'PH-CAV' },
  { name: 'Amadeo', province: 'PH-CAV' },
  { name: 'Bacoor', province: 'PH-CAV' },
  { name: 'Carmona', province: 'PH-CAV' },
  { name: 'Cavite City', province: 'PH-CAV' },
  { name: 'Dasmariñas', province: 'PH-CAV' },
  { name: 'General Emilio Aguinaldo', province: 'PH-CAV' },
  { name: 'General Mariano Alvarez', province: 'PH-CAV' },
  { name: 'General Trias', province: 'PH-CAV' },
  { name: 'Imus', province: 'PH-CAV' },
  { name: 'Indang', province: 'PH-CAV' },
  { name: 'Kawit', province: 'PH-CAV' },
  { name: 'Magallanes', province: 'PH-CAV' },
  { name: 'Maragondon', province: 'PH-CAV' },
  { name: 'Mendez (Mendez-Nuñez)', province: 'PH-CAV' },
  { name: 'Naic', province: 'PH-CAV' },
  { name: 'Noveleta', province: 'PH-CAV' },
  { name: 'Rosario', province: 'PH-CAV' },
  { name: 'Silang', province: 'PH-CAV' },
  { name: 'Tagaytay', province: 'PH-CAV' },
  { name: 'Tanza', province: 'PH-CAV' },
  { name: 'Ternate', province: 'PH-CAV' },
  { name: 'Trece Martires', province: 'PH-CAV' },
  { name: 'Alcantara', province: 'PH-CEB' },
  { name: 'Alcoy', province: 'PH-CEB' },
  { name: 'Alegria', province: 'PH-CEB' },
  { name: 'Aloguinsan', province: 'PH-CEB' },
  { name: 'Argao', province: 'PH-CEB' },
  { name: 'Asturias', province: 'PH-CEB' },
  { name: 'Badian', province: 'PH-CEB' },
  { name: 'Balamban', province: 'PH-CEB' },
  { name: 'Bantayan', province: 'PH-CEB' },
  { name: 'Barili', province: 'PH-CEB' },
  { name: 'Bogo', province: 'PH-CEB' },
  { name: 'Boljoon', province: 'PH-CEB' },
  { name: 'Borbon', province: 'PH-CEB' },
  { name: 'Carcar', province: 'PH-CEB' },
  { name: 'Carmen', province: 'PH-CEB' },
  { name: 'Catmon', province: 'PH-CEB' },
  { name: 'Cebu City', province: 'PH-CEB' },
  { name: 'Compostela', province: 'PH-CEB' },
  { name: 'Consolacion', province: 'PH-CEB' },
  { name: 'Cordova', province: 'PH-CEB' },
  { name: 'Daanbantayan', province: 'PH-CEB' },
  { name: 'Dalaguete', province: 'PH-CEB' },
  { name: 'Danao', province: 'PH-CEB' },
  { name: 'Dumanjug', province: 'PH-CEB' },
  { name: 'Ginatilan', province: 'PH-CEB' },
  { name: 'Lapu-Lapu (Opon)', province: 'PH-CEB' },
  { name: 'Liloan', province: 'PH-CEB' },
  { name: 'Madridejos', province: 'PH-CEB' },
  { name: 'Malabuyoc', province: 'PH-CEB' },
  { name: 'Mandaue', province: 'PH-CEB' },
  { name: 'Medellin', province: 'PH-CEB' },
  { name: 'Minglanilla', province: 'PH-CEB' },
  { name: 'Moalboal', province: 'PH-CEB' },
  { name: 'Naga', province: 'PH-CEB' },
  { name: 'Oslob', province: 'PH-CEB' },
  { name: 'Pilar', province: 'PH-CEB' },
  { name: 'Pinamungajan', province: 'PH-CEB' },
  { name: 'Poro', province: 'PH-CEB' },
  { name: 'Ronda', province: 'PH-CEB' },
  { name: 'Samboan', province: 'PH-CEB' },
  { name: 'San Fernando', province: 'PH-CEB' },
  { name: 'San Francisco', province: 'PH-CEB' },
  { name: 'San Remigio', province: 'PH-CEB' },
  { name: 'Santa Fe', province: 'PH-CEB' },
  { name: 'Santander', province: 'PH-CEB' },
  { name: 'Sibonga', province: 'PH-CEB' },
  { name: 'Sogod', province: 'PH-CEB' },
  { name: 'Tabogon', province: 'PH-CEB' },
  { name: 'Tabuelan', province: 'PH-CEB' },
  { name: 'Talisay', province: 'PH-CEB' },
  { name: 'Toledo', province: 'PH-CEB' },
  { name: 'Tuburan', province: 'PH-CEB' },
  { name: 'Tudela', province: 'PH-CEB' },
  { name: 'Compostela', province: 'PH-COM' },
  { name: 'Laak (San Vicente)', province: 'PH-COM' },
  { name: 'Mabini (Doña Alicia)', province: 'PH-COM' },
  { name: 'Maco', province: 'PH-COM' },
  { name: 'Maragusan (San Mariano)', province: 'PH-COM' },
  { name: 'Mawab', province: 'PH-COM' },
  { name: 'Monkayo', province: 'PH-COM' },
  { name: 'Montevista', province: 'PH-COM' },
  { name: 'Nabunturan', province: 'PH-COM' },
  { name: 'New Bataan', province: 'PH-COM' },
  { name: 'Pantukan', province: 'PH-COM' },
  { name: 'Alamada', province: 'PH-NCO' },
  { name: 'Aleosan', province: 'PH-NCO' },
  { name: 'Antipas', province: 'PH-NCO' },
  { name: 'Arakan', province: 'PH-NCO' },
  { name: 'Banisilan', province: 'PH-NCO' },
  { name: 'Carmen', province: 'PH-NCO' },
  { name: 'Kabacan', province: 'PH-NCO' },
  { name: 'Kidapawan', province: 'PH-NCO' },
  { name: 'Libungan', province: 'PH-NCO' },
  { name: 'M\'lang', province: 'PH-NCO' },
  { name: 'Magpet', province: 'PH-NCO' },
  { name: 'Makilala', province: 'PH-NCO' },
  { name: 'Matalam', province: 'PH-NCO' },
  { name: 'Midsayap', province: 'PH-NCO' },
  { name: 'Pigcawayan', province: 'PH-NCO' },
  { name: 'Pikit', province: 'PH-NCO' },
  { name: 'President Roxas', province: 'PH-NCO' },
  { name: 'Tulunan', province: 'PH-NCO' },
  { name: 'Asuncion (Saug)', province: 'PH-DAV' },
  { name: 'Braulio E. Dujali', province: 'PH-DAV' },
  { name: 'Carmen', province: 'PH-DAV' },
  { name: 'Kapalong', province: 'PH-DAV' },
  { name: 'New Corella', province: 'PH-DAV' },
  { name: 'Panabo', province: 'PH-DAV' },
  { name: 'Samal', province: 'PH-DAV' },
  { name: 'San Isidro', province: 'PH-DAV' },
  { name: 'Santo Tomas', province: 'PH-DAV' },
  { name: 'Tagum', province: 'PH-DAV' },
  { name: 'Talaingod', province: 'PH-DAV' },
  { name: 'Bansalan', province: 'PH-DAS' },
  { name: 'Davao City', province: 'PH-DAS' },
  { name: 'Digos', province: 'PH-DAS' },
  { name: 'Hagonoy', province: 'PH-DAS' },
  { name: 'Kiblawan', province: 'PH-DAS' },
  { name: 'Magsaysay', province: 'PH-DAS' },
  { name: 'Malalag', province: 'PH-DAS' },
  { name: 'Matanao', province: 'PH-DAS' },
  { name: 'Padada', province: 'PH-DAS' },
  { name: 'Santa Cruz', province: 'PH-DAS' },
  { name: 'Sulop', province: 'PH-DAS' },
  { name: 'Don Marcelino', province: 'PH-DVO' },
  { name: 'Jose Abad Santos (Trinidad)', province: 'PH-DVO' },
  { name: 'Malita', province: 'PH-DVO' },
  { name: 'Santa Maria', province: 'PH-DVO' },
  { name: 'Sarangani', province: 'PH-DVO' },
  { name: 'Baganga', province: 'PH-DAO' },
  { name: 'Banaybanay', province: 'PH-DAO' },
  { name: 'Boston', province: 'PH-DAO' },
  { name: 'Caraga', province: 'PH-DAO' },
  { name: 'Cateel', province: 'PH-DAO' },
  { name: 'Governor Generoso', province: 'PH-DAO' },
  { name: 'Lupon', province: 'PH-DAO' },
  { name: 'Manay', province: 'PH-DAO' },
  { name: 'Mati', province: 'PH-DAO' },
  { name: 'San Isidro', province: 'PH-DAO' },
  { name: 'Tarragona', province: 'PH-DAO' },
  { name: 'Basilisa (Rizal)', province: 'PH-DIN' },
  { name: 'Cagdianao', province: 'PH-DIN' },
  { name: 'Dinagat', province: 'PH-DIN' },
  { name: 'Libjo (Albor)', province: 'PH-DIN' },
  { name: 'Loreto', province: 'PH-DIN' },
  { name: 'San Jose', province: 'PH-DIN' },
  { name: 'Tubajon', province: 'PH-DIN' },
  { name: 'Arteche', province: 'PH-EAS' },
  { name: 'Balangiga', province: 'PH-EAS' },
  { name: 'Balangkayan', province: 'PH-EAS' },
  { name: 'Borongan', province: 'PH-EAS' },
  { name: 'Can-avid', province: 'PH-EAS' },
  { name: 'Dolores', province: 'PH-EAS' },
  { name: 'General MacArthur', province: 'PH-EAS' },
  { name: 'Giporlos', province: 'PH-EAS' },
  { name: 'Guiuan', province: 'PH-EAS' },
  { name: 'Hernani', province: 'PH-EAS' },
  { name: 'Jipapad', province: 'PH-EAS' },
  { name: 'Lawaan', province: 'PH-EAS' },
  { name: 'Llorente', province: 'PH-EAS' },
  { name: 'Maslog', province: 'PH-EAS' },
  { name: 'Maydolong', province: 'PH-EAS' },
  { name: 'Mercedes', province: 'PH-EAS' },
  { name: 'Oras', province: 'PH-EAS' },
  { name: 'Quinapondan', province: 'PH-EAS' },
  { name: 'Salcedo', province: 'PH-EAS' },
  { name: 'San Julian', province: 'PH-EAS' },
  { name: 'San Policarpo', province: 'PH-EAS' },
  { name: 'Sulat', province: 'PH-EAS' },
  { name: 'Taft', province: 'PH-EAS' },
  { name: 'Buenavista', province: 'PH-GUI' },
  { name: 'Jordan', province: 'PH-GUI' },
  { name: 'Nueva Valencia', province: 'PH-GUI' },
  { name: 'San Lorenzo', province: 'PH-GUI' },
  { name: 'Sibunag', province: 'PH-GUI' },
  { name: 'Aguinaldo', province: 'PH-IFU' },
  { name: 'Alfonso Lista (Potia)', province: 'PH-IFU' },
  { name: 'Asipulo', province: 'PH-IFU' },
  { name: 'Banaue', province: 'PH-IFU' },
  { name: 'Hingyon', province: 'PH-IFU' },
  { name: 'Hungduan', province: 'PH-IFU' },
  { name: 'Kiangan', province: 'PH-IFU' },
  { name: 'Lagawe', province: 'PH-IFU' },
  { name: 'Lamut', province: 'PH-IFU' },
  { name: 'Mayoyao', province: 'PH-IFU' },
  { name: 'Tinoc', province: 'PH-IFU' },
  { name: 'Adams', province: 'PH-ILN' },
  { name: 'Bacarra', province: 'PH-ILN' },
  { name: 'Badoc', province: 'PH-ILN' },
  { name: 'Bangui', province: 'PH-ILN' },
  { name: 'Banna (Espiritu)', province: 'PH-ILN' },
  { name: 'Batac', province: 'PH-ILN' },
  { name: 'Burgos', province: 'PH-ILN' },
  { name: 'Carasi', province: 'PH-ILN' },
  { name: 'Currimao', province: 'PH-ILN' },
  { name: 'Dingras', province: 'PH-ILN' },
  { name: 'Dumalneg', province: 'PH-ILN' },
  { name: 'Laoag', province: 'PH-ILN' },
  { name: 'Marcos', province: 'PH-ILN' },
  { name: 'Nueva Era', province: 'PH-ILN' },
  { name: 'Pagudpud', province: 'PH-ILN' },
  { name: 'Paoay', province: 'PH-ILN' },
  { name: 'Pasuquin', province: 'PH-ILN' },
  { name: 'Piddig', province: 'PH-ILN' },
  { name: 'Pinili', province: 'PH-ILN' },
  { name: 'San Nicolas', province: 'PH-ILN' },
  { name: 'Sarrat', province: 'PH-ILN' },
  { name: 'Solsona', province: 'PH-ILN' },
  { name: 'Vintar', province: 'PH-ILN' },
  { name: 'Alilem', province: 'PH-ILS' },
  { name: 'Banayoyo', province: 'PH-ILS' },
  { name: 'Bantay', province: 'PH-ILS' },
  { name: 'Burgos', province: 'PH-ILS' },
  { name: 'Cabugao', province: 'PH-ILS' },
  { name: 'Candon', province: 'PH-ILS' },
  { name: 'Caoayan', province: 'PH-ILS' },
  { name: 'Cervantes', province: 'PH-ILS' },
  { name: 'Galimuyod', province: 'PH-ILS' },
  { name: 'Gregorio del Pilar (Concepcion)', province: 'PH-ILS' },
  { name: 'Lidlidda', province: 'PH-ILS' },
  { name: 'Magsingal', province: 'PH-ILS' },
  { name: 'Nagbukel', province: 'PH-ILS' },
  { name: 'Narvacan', province: 'PH-ILS' },
  { name: 'Quirino (Angkaki)', province: 'PH-ILS' },
  { name: 'Salcedo (Baugen)', province: 'PH-ILS' },
  { name: 'San Emilio', province: 'PH-ILS' },
  { name: 'San Esteban', province: 'PH-ILS' },
  { name: 'San Ildefonso', province: 'PH-ILS' },
  { name: 'San Juan (Lapog)', province: 'PH-ILS' },
  { name: 'San Vicente', province: 'PH-ILS' },
  { name: 'Santa', province: 'PH-ILS' },
  { name: 'Santa Catalina', province: 'PH-ILS' },
  { name: 'Santa Cruz', province: 'PH-ILS' },
  { name: 'Santa Lucia', province: 'PH-ILS' },
  { name: 'Santa Maria', province: 'PH-ILS' },
  { name: 'Santiago', province: 'PH-ILS' },
  { name: 'Santo Domingo', province: 'PH-ILS' },
  { name: 'Sigay', province: 'PH-ILS' },
  { name: 'Sinait', province: 'PH-ILS' },
  { name: 'Sugpon', province: 'PH-ILS' },
  { name: 'Suyo', province: 'PH-ILS' },
  { name: 'Tagudin', province: 'PH-ILS' },
  { name: 'Vigan', province: 'PH-ILS' },
  { name: 'Ajuy', province: 'PH-ILI' },
  { name: 'Alimodian', province: 'PH-ILI' },
  { name: 'Anilao', province: 'PH-ILI' },
  { name: 'Badiangan', province: 'PH-ILI' },
  { name: 'Balasan', province: 'PH-ILI' },
  { name: 'Banate', province: 'PH-ILI' },
  { name: 'Barotac Nuevo', province: 'PH-ILI' },
  { name: 'Barotac Viejo', province: 'PH-ILI' },
  { name: 'Batad', province: 'PH-ILI' },
  { name: 'Bingawan', province: 'PH-ILI' },
  { name: 'Cabatuan', province: 'PH-ILI' },
  { name: 'Calinog', province: 'PH-ILI' },
  { name: 'Carles', province: 'PH-ILI' },
  { name: 'Concepcion', province: 'PH-ILI' },
  { name: 'Dingle', province: 'PH-ILI' },
  { name: 'Dueñas', province: 'PH-ILI' },
  { name: 'Dumangas', province: 'PH-ILI' },
  { name: 'Estancia', province: 'PH-ILI' },
  { name: 'Guimbal', province: 'PH-ILI' },
  { name: 'Igbaras', province: 'PH-ILI' },
  { name: 'Iloilo City', province: 'PH-ILI' },
  { name: 'Janiuay', province: 'PH-ILI' },
  { name: 'Lambunao', province: 'PH-ILI' },
  { name: 'Leganes', province: 'PH-ILI' },
  { name: 'Lemery', province: 'PH-ILI' },
  { name: 'Leon', province: 'PH-ILI' },
  { name: 'Maasin', province: 'PH-ILI' },
  { name: 'Miagao', province: 'PH-ILI' },
  { name: 'Mina', province: 'PH-ILI' },
  { name: 'New Lucena', province: 'PH-ILI' },
  { name: 'Oton', province: 'PH-ILI' },
  { name: 'Passi', province: 'PH-ILI' },
  { name: 'Pavia', province: 'PH-ILI' },
  { name: 'Pototan', province: 'PH-ILI' },
  { name: 'San Dionisio', province: 'PH-ILI' },
  { name: 'San Enrique', province: 'PH-ILI' },
  { name: 'San Joaquin', province: 'PH-ILI' },
  { name: 'San Miguel', province: 'PH-ILI' },
  { name: 'San Rafael', province: 'PH-ILI' },
  { name: 'Santa Barbara', province: 'PH-ILI' },
  { name: 'Sara', province: 'PH-ILI' },
  { name: 'Tigbauan', province: 'PH-ILI' },
  { name: 'Tubungan', province: 'PH-ILI' },
  { name: 'Zarraga', province: 'PH-ILI' },
  { name: 'Alicia', province: 'PH-ISA' },
  { name: 'Angadanan', province: 'PH-ISA' },
  { name: 'Aurora', province: 'PH-ISA' },
  { name: 'Benito Soliven', province: 'PH-ISA' },
  { name: 'Burgos', province: 'PH-ISA' },
  { name: 'Cabagan', province: 'PH-ISA' },
  { name: 'Cabatuan', province: 'PH-ISA' },
  { name: 'Cauayan', province: 'PH-ISA' },
  { name: 'Cordon', province: 'PH-ISA' },
  { name: 'Delfin Albano (Magsaysay)', province: 'PH-ISA' },
  { name: 'Dinapigue', province: 'PH-ISA' },
  { name: 'Divilacan', province: 'PH-ISA' },
  { name: 'Echague', province: 'PH-ISA' },
  { name: 'Gamu', province: 'PH-ISA' },
  { name: 'Ilagan', province: 'PH-ISA' },
  { name: 'Jones', province: 'PH-ISA' },
  { name: 'Luna', province: 'PH-ISA' },
  { name: 'Maconacon', province: 'PH-ISA' },
  { name: 'Mallig', province: 'PH-ISA' },
  { name: 'Naguilian', province: 'PH-ISA' },
  { name: 'Palanan', province: 'PH-ISA' },
  { name: 'Quezon', province: 'PH-ISA' },
  { name: 'Quirino', province: 'PH-ISA' },
  { name: 'Ramon', province: 'PH-ISA' },
  { name: 'Reina Mercedes', province: 'PH-ISA' },
  { name: 'Roxas', province: 'PH-ISA' },
  { name: 'San Agustin', province: 'PH-ISA' },
  { name: 'San Guillermo', province: 'PH-ISA' },
  { name: 'San Isidro', province: 'PH-ISA' },
  { name: 'San Manuel (Callang)', province: 'PH-ISA' },
  { name: 'San Mariano', province: 'PH-ISA' },
  { name: 'San Mateo', province: 'PH-ISA' },
  { name: 'San Pablo', province: 'PH-ISA' },
  { name: 'Santa Maria', province: 'PH-ISA' },
  { name: 'Santiago', province: 'PH-ISA' },
  { name: 'Santo Tomas', province: 'PH-ISA' },
  { name: 'Tumauini', province: 'PH-ISA' },
  { name: 'Balbalan', province: 'PH-KAL' },
  { name: 'Lubuagan', province: 'PH-KAL' },
  { name: 'Pasil', province: 'PH-KAL' },
  { name: 'Pinukpuk', province: 'PH-KAL' },
  { name: 'Rizal (Liwan)', province: 'PH-KAL' },
  { name: 'Tabuk', province: 'PH-KAL' },
  { name: 'Tanudan', province: 'PH-KAL' },
  { name: 'Tinglayan', province: 'PH-KAL' },
  { name: 'Agoo', province: 'PH-LUN' },
  { name: 'Aringay', province: 'PH-LUN' },
  { name: 'Bacnotan', province: 'PH-LUN' },
  { name: 'Bagulin', province: 'PH-LUN' },
  { name: 'Balaoan', province: 'PH-LUN' },
  { name: 'Bangar', province: 'PH-LUN' },
  { name: 'Bauang', province: 'PH-LUN' },
  { name: 'Burgos', province: 'PH-LUN' },
  { name: 'Caba', province: 'PH-LUN' },
  { name: 'Luna', province: 'PH-LUN' },
  { name: 'Naguilian', province: 'PH-LUN' },
  { name: 'Pugo', province: 'PH-LUN' },
  { name: 'Rosario', province: 'PH-LUN' },
  { name: 'San Fernando', province: 'PH-LUN' },
  { name: 'San Gabriel', province: 'PH-LUN' },
  { name: 'San Juan', province: 'PH-LUN' },
  { name: 'Santo Tomas', province: 'PH-LUN' },
  { name: 'Santol', province: 'PH-LUN' },
  { name: 'Sudipen', province: 'PH-LUN' },
  { name: 'Tubao', province: 'PH-LUN' },
  { name: 'Alaminos', province: 'PH-LAG' },
  { name: 'Bay', province: 'PH-LAG' },
  { name: 'Biñan', province: 'PH-LAG' },
  { name: 'Cabuyao', province: 'PH-LAG' },
  { name: 'Calamba', province: 'PH-LAG' },
  { name: 'Calauan', province: 'PH-LAG' },
  { name: 'Cavinti', province: 'PH-LAG' },
  { name: 'Famy', province: 'PH-LAG' },
  { name: 'Kalayaan', province: 'PH-LAG' },
  { name: 'Liliw', province: 'PH-LAG' },
  { name: 'Los Baños', province: 'PH-LAG' },
  { name: 'Luisiana', province: 'PH-LAG' },
  { name: 'Lumban', province: 'PH-LAG' },
  { name: 'Mabitac', province: 'PH-LAG' },
  { name: 'Magdalena', province: 'PH-LAG' },
  { name: 'Majayjay', province: 'PH-LAG' },
  { name: 'Nagcarlan', province: 'PH-LAG' },
  { name: 'Paete', province: 'PH-LAG' },
  { name: 'Pagsanjan', province: 'PH-LAG' },
  { name: 'Pakil', province: 'PH-LAG' },
  { name: 'Pangil', province: 'PH-LAG' },
  { name: 'Pila', province: 'PH-LAG' },
  { name: 'Rizal', province: 'PH-LAG' },
  { name: 'San Pablo', province: 'PH-LAG' },
  { name: 'San Pedro', province: 'PH-LAG' },
  { name: 'Santa Cruz', province: 'PH-LAG' },
  { name: 'Santa Maria', province: 'PH-LAG' },
  { name: 'Santa Rosa', province: 'PH-LAG' },
  { name: 'Siniloan', province: 'PH-LAG' },
  { name: 'Victoria', province: 'PH-LAG' },
  { name: 'Bacolod', province: 'PH-LAN' },
  { name: 'Baloi', province: 'PH-LAN' },
  { name: 'Baroy', province: 'PH-LAN' },
  { name: 'Iligan', province: 'PH-LAN' },
  { name: 'Kapatagan', province: 'PH-LAN' },
  { name: 'Kauswagan', province: 'PH-LAN' },
  { name: 'Kolambugan', province: 'PH-LAN' },
  { name: 'Lala', province: 'PH-LAN' },
  { name: 'Linamon', province: 'PH-LAN' },
  { name: 'Magsaysay', province: 'PH-LAN' },
  { name: 'Maigo', province: 'PH-LAN' },
  { name: 'Matungao', province: 'PH-LAN' },
  { name: 'Munai', province: 'PH-LAN' },
  { name: 'Nunungan', province: 'PH-LAN' },
  { name: 'Pantao Ragat', province: 'PH-LAN' },
  { name: 'Pantar', province: 'PH-LAN' },
  { name: 'Poona Piagapo', province: 'PH-LAN' },
  { name: 'Salvador', province: 'PH-LAN' },
  { name: 'Sapad', province: 'PH-LAN' },
  { name: 'Sultan Naga Dimaporo (Karomatan)', province: 'PH-LAN' },
  { name: 'Tagoloan', province: 'PH-LAN' },
  { name: 'Tangcal', province: 'PH-LAN' },
  { name: 'Tubod', province: 'PH-LAN' },
  { name: 'Amai Manabilang (Bumbaran)', province: 'PH-LAS' },
  { name: 'Bacolod-Kalawi (Bacolod-Grande)', province: 'PH-LAS' },
  { name: 'Balabagan', province: 'PH-LAS' },
  { name: 'Balindong (Watu)', province: 'PH-LAS' },
  { name: 'Bayang', province: 'PH-LAS' },
  { name: 'Binidayan', province: 'PH-LAS' },
  { name: 'Buadiposo-Buntong', province: 'PH-LAS' },
  { name: 'Bubong', province: 'PH-LAS' },
  { name: 'Butig', province: 'PH-LAS' },
  { name: 'Calanogas', province: 'PH-LAS' },
  { name: 'Ditsaan-Ramain', province: 'PH-LAS' },
  { name: 'Ganassi', province: 'PH-LAS' },
  { name: 'Kapai', province: 'PH-LAS' },
  { name: 'Kapatagan', province: 'PH-LAS' },
  { name: 'Lumba-Bayabao (Maguing)', province: 'PH-LAS' },
  { name: 'Lumbaca-Unayan', province: 'PH-LAS' },
  { name: 'Lumbatan', province: 'PH-LAS' },
  { name: 'Lumbayanague', province: 'PH-LAS' },
  { name: 'Madalum', province: 'PH-LAS' },
  { name: 'Madamba', province: 'PH-LAS' },
  { name: 'Maguing', province: 'PH-LAS' },
  { name: 'Malabang', province: 'PH-LAS' },
  { name: 'Marantao', province: 'PH-LAS' },
  { name: 'Marawi', province: 'PH-LAS' },
  { name: 'Marogong', province: 'PH-LAS' },
  { name: 'Masiu', province: 'PH-LAS' },
  { name: 'Mulondo', province: 'PH-LAS' },
  { name: 'Pagayawan (Tatarikan)', province: 'PH-LAS' },
  { name: 'Piagapo', province: 'PH-LAS' },
  { name: 'Picong (Sultan Gumander)', province: 'PH-LAS' },
  { name: 'Poona Bayabao (Gata)', province: 'PH-LAS' },
  { name: 'Pualas', province: 'PH-LAS' },
  { name: 'Saguiaran', province: 'PH-LAS' },
  { name: 'Sultan Dumalondong', province: 'PH-LAS' },
  { name: 'Tagoloan II', province: 'PH-LAS' },
  { name: 'Tamparan', province: 'PH-LAS' },
  { name: 'Taraka', province: 'PH-LAS' },
  { name: 'Tubaran', province: 'PH-LAS' },
  { name: 'Tugaya', province: 'PH-LAS' },
  { name: 'Wao', province: 'PH-LAS' },
  { name: 'Abuyog', province: 'PH-LEY' },
  { name: 'Alangalang', province: 'PH-LEY' },
  { name: 'Albuera', province: 'PH-LEY' },
  { name: 'Babatngon', province: 'PH-LEY' },
  { name: 'Barugo', province: 'PH-LEY' },
  { name: 'Bato', province: 'PH-LEY' },
  { name: 'Baybay', province: 'PH-LEY' },
  { name: 'Burauen', province: 'PH-LEY' },
  { name: 'Calubian', province: 'PH-LEY' },
  { name: 'Capoocan', province: 'PH-LEY' },
  { name: 'Carigara', province: 'PH-LEY' },
  { name: 'Dagami', province: 'PH-LEY' },
  { name: 'Dulag', province: 'PH-LEY' },
  { name: 'Hilongos', province: 'PH-LEY' },
  { name: 'Hindang', province: 'PH-LEY' },
  { name: 'Inopacan', province: 'PH-LEY' },
  { name: 'Isabel', province: 'PH-LEY' },
  { name: 'Jaro', province: 'PH-LEY' },
  { name: 'Javier (Bugho)', province: 'PH-LEY' },
  { name: 'Julita', province: 'PH-LEY' },
  { name: 'Kananga', province: 'PH-LEY' },
  { name: 'La Paz', province: 'PH-LEY' },
  { name: 'Leyte', province: 'PH-LEY' },
  { name: 'MacArthur', province: 'PH-LEY' },
  { name: 'Mahaplag', province: 'PH-LEY' },
  { name: 'Matag-ob', province: 'PH-LEY' },
  { name: 'Matalom', province: 'PH-LEY' },
  { name: 'Mayorga', province: 'PH-LEY' },
  { name: 'Merida', province: 'PH-LEY' },
  { name: 'Ormoc', province: 'PH-LEY' },
  { name: 'Palo', province: 'PH-LEY' },
  { name: 'Palompon', province: 'PH-LEY' },
  { name: 'Pastrana', province: 'PH-LEY' },
  { name: 'San Isidro', province: 'PH-LEY' },
  { name: 'San Miguel', province: 'PH-LEY' },
  { name: 'Santa Fe', province: 'PH-LEY' },
  { name: 'Tabango', province: 'PH-LEY' },
  { name: 'Tabontabon', province: 'PH-LEY' },
  { name: 'Tacloban', province: 'PH-LEY' },
  { name: 'Tanauan', province: 'PH-LEY' },
  { name: 'Tolosa', province: 'PH-LEY' },
  { name: 'Tunga', province: 'PH-LEY' },
  { name: 'Villaba', province: 'PH-LEY' },
  { name: 'Ampatuan', province: 'PH-MAG' },
  { name: 'Barira', province: 'PH-MAG' },
  { name: 'Buldon', province: 'PH-MAG' },
  { name: 'Buluan', province: 'PH-MAG' },
  { name: 'Cotabato City', province: 'PH-MAG' },
  { name: 'Datu Abdullah Sangki', province: 'PH-MAG' },
  { name: 'Datu Anggal Midtimbang', province: 'PH-MAG' },
  { name: 'Datu Blah T. Sinsuat', province: 'PH-MAG' },
  { name: 'Datu Hoffer Ampatuan', province: 'PH-MAG' },
  { name: 'Datu Montawal (Pagagawan)', province: 'PH-MAG' },
  { name: 'Datu Odin Sinsuat (Dinaig)', province: 'PH-MAG' },
  { name: 'Datu Paglas', province: 'PH-MAG' },
  { name: 'Datu Piang (Dulawan)', province: 'PH-MAG' },
  { name: 'Datu Salibo', province: 'PH-MAG' },
  { name: 'Datu Saudi-Ampatuan', province: 'PH-MAG' },
  { name: 'Datu Unsay', province: 'PH-MAG' },
  { name: 'General Salipada K. Pendatun', province: 'PH-MAG' },
  { name: 'Guindulungan', province: 'PH-MAG' },
  { name: 'Kabuntalan (Tumbao)', province: 'PH-MAG' },
  { name: 'Mamasapano', province: 'PH-MAG' },
  { name: 'Mangudadatu', province: 'PH-MAG' },
  { name: 'Matanog', province: 'PH-MAG' },
  { name: 'Northern Kabuntalan', province: 'PH-MAG' },
  { name: 'Pagalungan', province: 'PH-MAG' },
  { name: 'Paglat', province: 'PH-MAG' },
  { name: 'Pandag', province: 'PH-MAG' },
  { name: 'Parang', province: 'PH-MAG' },
  { name: 'Rajah Buayan', province: 'PH-MAG' },
  { name: 'Shariff Aguak (Maganoy)', province: 'PH-MAG' },
  { name: 'Shariff Saydona Mustapha', province: 'PH-MAG' },
  { name: 'South Upi', province: 'PH-MAG' },
  { name: 'Sultan Kudarat (Nuling)', province: 'PH-MAG' },
  { name: 'Sultan Mastura', province: 'PH-MAG' },
  { name: 'Sultan sa Barongis (Lambayong)', province: 'PH-MAG' },
  { name: 'Sultan Sumagka (Talitay)', province: 'PH-MAG' },
  { name: 'Talayan', province: 'PH-MAG' },
  { name: 'Upi', province: 'PH-MAG' },
  { name: 'Boac', province: 'PH-MAD' },
  { name: 'Buenavista', province: 'PH-MAD' },
  { name: 'Gasan', province: 'PH-MAD' },
  { name: 'Mogpog', province: 'PH-MAD' },
  { name: 'Santa Cruz', province: 'PH-MAD' },
  { name: 'Torrijos', province: 'PH-MAD' },
  { name: 'Aroroy', province: 'PH-MAS' },
  { name: 'Baleno', province: 'PH-MAS' },
  { name: 'Balud', province: 'PH-MAS' },
  { name: 'Batuan', province: 'PH-MAS' },
  { name: 'Cataingan', province: 'PH-MAS' },
  { name: 'Cawayan', province: 'PH-MAS' },
  { name: 'Claveria', province: 'PH-MAS' },
  { name: 'Dimasalang', province: 'PH-MAS' },
  { name: 'Esperanza', province: 'PH-MAS' },
  { name: 'Mandaon', province: 'PH-MAS' },
  { name: 'Masbate City', province: 'PH-MAS' },
  { name: 'Milagros', province: 'PH-MAS' },
  { name: 'Mobo', province: 'PH-MAS' },
  { name: 'Monreal', province: 'PH-MAS' },
  { name: 'Palanas', province: 'PH-MAS' },
  { name: 'Pio V. Corpuz (Limbuhan)', province: 'PH-MAS' },
  { name: 'Placer', province: 'PH-MAS' },
  { name: 'San Fernando', province: 'PH-MAS' },
  { name: 'San Jacinto', province: 'PH-MAS' },
  { name: 'San Pascual', province: 'PH-MAS' },
  { name: 'Uson', province: 'PH-MAS' },
  { name: 'Aloran', province: 'PH-MSC' },
  { name: 'Baliangao', province: 'PH-MSC' },
  { name: 'Bonifacio', province: 'PH-MSC' },
  { name: 'Calamba', province: 'PH-MSC' },
  { name: 'Clarin', province: 'PH-MSC' },
  { name: 'Concepcion', province: 'PH-MSC' },
  { name: 'Don Victoriano Chiongbian (Don Mariano Marcos)', province: 'PH-MSC' },
  { name: 'Jimenez', province: 'PH-MSC' },
  { name: 'Lopez Jaena', province: 'PH-MSC' },
  { name: 'Oroquieta', province: 'PH-MSC' },
  { name: 'Ozamiz', province: 'PH-MSC' },
  { name: 'Panaon', province: 'PH-MSC' },
  { name: 'Plaridel', province: 'PH-MSC' },
  { name: 'Sapang Dalaga', province: 'PH-MSC' },
  { name: 'Sinacaban', province: 'PH-MSC' },
  { name: 'Tangub', province: 'PH-MSC' },
  { name: 'Tudela', province: 'PH-MSC' },
  { name: 'Alubijid', province: 'PH-MSR' },
  { name: 'Balingasag', province: 'PH-MSR' },
  { name: 'Balingoan', province: 'PH-MSR' },
  { name: 'Binuangan', province: 'PH-MSR' },
  { name: 'Cagayan de Oro', province: 'PH-MSR' },
  { name: 'Claveria', province: 'PH-MSR' },
  { name: 'El Salvador', province: 'PH-MSR' },
  { name: 'Gingoog', province: 'PH-MSR' },
  { name: 'Gitagum', province: 'PH-MSR' },
  { name: 'Initao', province: 'PH-MSR' },
  { name: 'Jasaan', province: 'PH-MSR' },
  { name: 'Kinoguitan', province: 'PH-MSR' },
  { name: 'Lagonglong', province: 'PH-MSR' },
  { name: 'Laguindingan', province: 'PH-MSR' },
  { name: 'Libertad', province: 'PH-MSR' },
  { name: 'Lugait', province: 'PH-MSR' },
  { name: 'Magsaysay (Linugos)', province: 'PH-MSR' },
  { name: 'Manticao', province: 'PH-MSR' },
  { name: 'Medina', province: 'PH-MSR' },
  { name: 'Naawan', province: 'PH-MSR' },
  { name: 'Opol', province: 'PH-MSR' },
  { name: 'Salay', province: 'PH-MSR' },
  { name: 'Sugbongcogon', province: 'PH-MSR' },
  { name: 'Tagoloan', province: 'PH-MSR' },
  { name: 'Talisayan', province: 'PH-MSR' },
  { name: 'Villanueva', province: 'PH-MSR' },
  { name: 'Barlig', province: 'PH-MOU' },
  { name: 'Bauko', province: 'PH-MOU' },
  { name: 'Besao', province: 'PH-MOU' },
  { name: 'Bontoc', province: 'PH-MOU' },
  { name: 'Natonin', province: 'PH-MOU' },
  { name: 'Paracelis', province: 'PH-MOU' },
  { name: 'Sabangan', province: 'PH-MOU' },
  { name: 'Sadanga', province: 'PH-MOU' },
  { name: 'Sagada', province: 'PH-MOU' },
  { name: 'Tadian', province: 'PH-MOU' },
  { name: 'Caloocan', province: 'PH-00' },
  { name: 'Las Piñas', province: 'PH-00' },
  { name: 'Makati', province: 'PH-00' },
  { name: 'Malabon', province: 'PH-00' },
  { name: 'Mandaluyong', province: 'PH-00' },
  { name: 'Manila', province: 'PH-00' },
  { name: 'Marikina', province: 'PH-00' },
  { name: 'Muntinlupa', province: 'PH-00' },
  { name: 'Navotas', province: 'PH-00' },
  { name: 'Parañaque', province: 'PH-00' },
  { name: 'Pasay', province: 'PH-00' },
  { name: 'Pasig', province: 'PH-00' },
  { name: 'Pateros', province: 'PH-00' },
  { name: 'Quezon City', province: 'PH-00' },
  { name: 'San Juan', province: 'PH-00' },
  { name: 'Taguig', province: 'PH-00' },
  { name: 'Valenzuela', province: 'PH-00' },
  { name: 'Bacolod', province: 'PH-NEC' },
  { name: 'Bago', province: 'PH-NEC' },
  { name: 'Binalbagan', province: 'PH-NEC' },
  { name: 'Cadiz', province: 'PH-NEC' },
  { name: 'Calatrava', province: 'PH-NEC' },
  { name: 'Candoni', province: 'PH-NEC' },
  { name: 'Cauayan', province: 'PH-NEC' },
  { name: 'Enrique B. Magalona (Saravia)', province: 'PH-NEC' },
  { name: 'Escalante', province: 'PH-NEC' },
  { name: 'Himamaylan', province: 'PH-NEC' },
  { name: 'Hinigaran', province: 'PH-NEC' },
  { name: 'Hinoba-an (Asia)', province: 'PH-NEC' },
  { name: 'Ilog', province: 'PH-NEC' },
  { name: 'Isabela', province: 'PH-NEC' },
  { name: 'Kabankalan', province: 'PH-NEC' },
  { name: 'La Carlota', province: 'PH-NEC' },
  { name: 'La Castellana', province: 'PH-NEC' },
  { name: 'Manapla', province: 'PH-NEC' },
  { name: 'Moises Padilla (Magallon)', province: 'PH-NEC' },
  { name: 'Murcia', province: 'PH-NEC' },
  { name: 'Pontevedra', province: 'PH-NEC' },
  { name: 'Pulupandan', province: 'PH-NEC' },
  { name: 'Sagay', province: 'PH-NEC' },
  { name: 'Salvador Benedicto', province: 'PH-NEC' },
  { name: 'San Carlos', province: 'PH-NEC' },
  { name: 'San Enrique', province: 'PH-NEC' },
  { name: 'Silay', province: 'PH-NEC' },
  { name: 'Sipalay', province: 'PH-NEC' },
  { name: 'Talisay', province: 'PH-NEC' },
  { name: 'Toboso', province: 'PH-NEC' },
  { name: 'Valladolid', province: 'PH-NEC' },
  { name: 'Victorias', province: 'PH-NEC' },
  { name: 'Amlan (Ayuquitan)', province: 'PH-NER' },
  { name: 'Ayungon', province: 'PH-NER' },
  { name: 'Bacong', province: 'PH-NER' },
  { name: 'Bais', province: 'PH-NER' },
  { name: 'Basay', province: 'PH-NER' },
  { name: 'Bayawan (Tulong)', province: 'PH-NER' },
  { name: 'Bindoy (Payabon)', province: 'PH-NER' },
  { name: 'Canlaon', province: 'PH-NER' },
  { name: 'Dauin', province: 'PH-NER' },
  { name: 'Dumaguete', province: 'PH-NER' },
  { name: 'Guihulngan', province: 'PH-NER' },
  { name: 'Jimalalud', province: 'PH-NER' },
  { name: 'La Libertad', province: 'PH-NER' },
  { name: 'Mabinay', province: 'PH-NER' },
  { name: 'Manjuyod', province: 'PH-NER' },
  { name: 'Pamplona', province: 'PH-NER' },
  { name: 'San Jose', province: 'PH-NER' },
  { name: 'Santa Catalina', province: 'PH-NER' },
  { name: 'Siaton', province: 'PH-NER' },
  { name: 'Sibulan', province: 'PH-NER' },
  { name: 'Tanjay', province: 'PH-NER' },
  { name: 'Tayasan', province: 'PH-NER' },
  { name: 'Valencia (Luzurriaga)', province: 'PH-NER' },
  { name: 'Vallehermoso', province: 'PH-NER' },
  { name: 'Zamboanguita', province: 'PH-NER' },
  { name: 'Allen', province: 'PH-NSA' },
  { name: 'Biri', province: 'PH-NSA' },
  { name: 'Bobon', province: 'PH-NSA' },
  { name: 'Capul', province: 'PH-NSA' },
  { name: 'Catarman', province: 'PH-NSA' },
  { name: 'Catubig', province: 'PH-NSA' },
  { name: 'Gamay', province: 'PH-NSA' },
  { name: 'Laoang', province: 'PH-NSA' },
  { name: 'Lapinig', province: 'PH-NSA' },
  { name: 'Las Navas', province: 'PH-NSA' },
  { name: 'Lavezares', province: 'PH-NSA' },
  { name: 'Lope de Vega', province: 'PH-NSA' },
  { name: 'Mapanas', province: 'PH-NSA' },
  { name: 'Mondragon', province: 'PH-NSA' },
  { name: 'Palapag', province: 'PH-NSA' },
  { name: 'Pambujan', province: 'PH-NSA' },
  { name: 'Rosario', province: 'PH-NSA' },
  { name: 'San Antonio', province: 'PH-NSA' },
  { name: 'San Isidro', province: 'PH-NSA' },
  { name: 'San Jose', province: 'PH-NSA' },
  { name: 'San Roque', province: 'PH-NSA' },
  { name: 'San Vicente', province: 'PH-NSA' },
  { name: 'Silvino Lobos', province: 'PH-NSA' },
  { name: 'Victoria', province: 'PH-NSA' },
  { name: 'Aliaga', province: 'PH-NUE' },
  { name: 'Bongabon', province: 'PH-NUE' },
  { name: 'Cabanatuan', province: 'PH-NUE' },
  { name: 'Cabiao', province: 'PH-NUE' },
  { name: 'Carranglan', province: 'PH-NUE' },
  { name: 'Cuyapo', province: 'PH-NUE' },
  { name: 'Gabaldon (Bitulok & Sabani)', province: 'PH-NUE' },
  { name: 'Gapan', province: 'PH-NUE' },
  { name: 'General Mamerto Natividad', province: 'PH-NUE' },
  { name: 'General Tinio (Papaya)', province: 'PH-NUE' },
  { name: 'Guimba', province: 'PH-NUE' },
  { name: 'Jaen', province: 'PH-NUE' },
  { name: 'Laur', province: 'PH-NUE' },
  { name: 'Licab', province: 'PH-NUE' },
  { name: 'Llanera', province: 'PH-NUE' },
  { name: 'Lupao', province: 'PH-NUE' },
  { name: 'Muñoz', province: 'PH-NUE' },
  { name: 'Nampicuan', province: 'PH-NUE' },
  { name: 'Palayan', province: 'PH-NUE' },
  { name: 'Pantabangan', province: 'PH-NUE' },
  { name: 'Peñaranda', province: 'PH-NUE' },
  { name: 'Quezon', province: 'PH-NUE' },
  { name: 'Rizal', province: 'PH-NUE' },
  { name: 'San Antonio', province: 'PH-NUE' },
  { name: 'San Isidro', province: 'PH-NUE' },
  { name: 'San Jose', province: 'PH-NUE' },
  { name: 'San Leonardo', province: 'PH-NUE' },
  { name: 'Santa Rosa', province: 'PH-NUE' },
  { name: 'Santo Domingo', province: 'PH-NUE' },
  { name: 'Talavera', province: 'PH-NUE' },
  { name: 'Talugtug', province: 'PH-NUE' },
  { name: 'Zaragoza', province: 'PH-NUE' },
  { name: 'Alfonso Castañeda', province: 'PH-NUV' },
  { name: 'Ambaguio', province: 'PH-NUV' },
  { name: 'Aritao', province: 'PH-NUV' },
  { name: 'Bagabag', province: 'PH-NUV' },
  { name: 'Bambang', province: 'PH-NUV' },
  { name: 'Bayombong', province: 'PH-NUV' },
  { name: 'Diadi', province: 'PH-NUV' },
  { name: 'Dupax del Norte', province: 'PH-NUV' },
  { name: 'Dupax del Sur', province: 'PH-NUV' },
  { name: 'Kasibu', province: 'PH-NUV' },
  { name: 'Kayapa', province: 'PH-NUV' },
  { name: 'Quezon', province: 'PH-NUV' },
  { name: 'Santa Fe (Imugan)', province: 'PH-NUV' },
  { name: 'Solano', province: 'PH-NUV' },
  { name: 'Villaverde (Ibung)', province: 'PH-NUV' },
  { name: 'Abra de Ilog', province: 'PH-MDC' },
  { name: 'Calintaan', province: 'PH-MDC' },
  { name: 'Looc', province: 'PH-MDC' },
  { name: 'Lubang', province: 'PH-MDC' },
  { name: 'Magsaysay', province: 'PH-MDC' },
  { name: 'Mamburao', province: 'PH-MDC' },
  { name: 'Paluan', province: 'PH-MDC' },
  { name: 'Rizal', province: 'PH-MDC' },
  { name: 'Sablayan', province: 'PH-MDC' },
  { name: 'San Jose', province: 'PH-MDC' },
  { name: 'Santa Cruz', province: 'PH-MDC' },
  { name: 'Baco', province: 'PH-MDR' },
  { name: 'Bansud', province: 'PH-MDR' },
  { name: 'Bongabong', province: 'PH-MDR' },
  { name: 'Bulalacao (San Pedro)', province: 'PH-MDR' },
  { name: 'Calapan', province: 'PH-MDR' },
  { name: 'Gloria', province: 'PH-MDR' },
  { name: 'Mansalay', province: 'PH-MDR' },
  { name: 'Naujan', province: 'PH-MDR' },
  { name: 'Pinamalayan', province: 'PH-MDR' },
  { name: 'Pola', province: 'PH-MDR' },
  { name: 'Puerto Galera', province: 'PH-MDR' },
  { name: 'Roxas', province: 'PH-MDR' },
  { name: 'San Teodoro', province: 'PH-MDR' },
  { name: 'Socorro', province: 'PH-MDR' },
  { name: 'Victoria', province: 'PH-MDR' },
  { name: 'Aborlan', province: 'PH-PLW' },
  { name: 'Agutaya', province: 'PH-PLW' },
  { name: 'Araceli', province: 'PH-PLW' },
  { name: 'Balabac', province: 'PH-PLW' },
  { name: 'Bataraza', province: 'PH-PLW' },
  { name: 'Brooke\'s Point', province: 'PH-PLW' },
  { name: 'Busuanga', province: 'PH-PLW' },
  { name: 'Cagayancillo', province: 'PH-PLW' },
  { name: 'Coron', province: 'PH-PLW' },
  { name: 'Culion', province: 'PH-PLW' },
  { name: 'Cuyo', province: 'PH-PLW' },
  { name: 'Dumaran', province: 'PH-PLW' },
  { name: 'El Nido (Bacuit)', province: 'PH-PLW' },
  { name: 'Kalayaan', province: 'PH-PLW' },
  { name: 'Linapacan', province: 'PH-PLW' },
  { name: 'Magsaysay', province: 'PH-PLW' },
  { name: 'Narra', province: 'PH-PLW' },
  { name: 'Puerto Princesa', province: 'PH-PLW' },
  { name: 'Quezon', province: 'PH-PLW' },
  { name: 'Rizal (Marcos)', province: 'PH-PLW' },
  { name: 'Roxas', province: 'PH-PLW' },
  { name: 'San Vicente', province: 'PH-PLW' },
  { name: 'Sofronio Española', province: 'PH-PLW' },
  { name: 'Taytay', province: 'PH-PLW' },
  { name: 'Angeles', province: 'PH-PAM' },
  { name: 'Apalit', province: 'PH-PAM' },
  { name: 'Arayat', province: 'PH-PAM' },
  { name: 'Bacolor', province: 'PH-PAM' },
  { name: 'Candaba', province: 'PH-PAM' },
  { name: 'Floridablanca', province: 'PH-PAM' },
  { name: 'Guagua', province: 'PH-PAM' },
  { name: 'Lubao', province: 'PH-PAM' },
  { name: 'Mabalacat', province: 'PH-PAM' },
  { name: 'Macabebe', province: 'PH-PAM' },
  { name: 'Magalang', province: 'PH-PAM' },
  { name: 'Masantol', province: 'PH-PAM' },
  { name: 'Mexico', province: 'PH-PAM' },
  { name: 'Minalin', province: 'PH-PAM' },
  { name: 'Porac', province: 'PH-PAM' },
  { name: 'San Fernando', province: 'PH-PAM' },
  { name: 'San Luis', province: 'PH-PAM' },
  { name: 'San Simon', province: 'PH-PAM' },
  { name: 'Santa Ana', province: 'PH-PAM' },
  { name: 'Santa Rita', province: 'PH-PAM' },
  { name: 'Santo Tomas', province: 'PH-PAM' },
  { name: 'Sasmuan (Sexmoan)', province: 'PH-PAM' },
  { name: 'Agno', province: 'PH-PAN' },
  { name: 'Aguilar', province: 'PH-PAN' },
  { name: 'Alaminos', province: 'PH-PAN' },
  { name: 'Alcala', province: 'PH-PAN' },
  { name: 'Anda', province: 'PH-PAN' },
  { name: 'Asingan', province: 'PH-PAN' },
  { name: 'Balungao', province: 'PH-PAN' },
  { name: 'Bani', province: 'PH-PAN' },
  { name: 'Basista', province: 'PH-PAN' },
  { name: 'Bautista', province: 'PH-PAN' },
  { name: 'Bayambang', province: 'PH-PAN' },
  { name: 'Binalonan', province: 'PH-PAN' },
  { name: 'Binmaley', province: 'PH-PAN' },
  { name: 'Bolinao', province: 'PH-PAN' },
  { name: 'Bugallon', province: 'PH-PAN' },
  { name: 'Burgos', province: 'PH-PAN' },
  { name: 'Calasiao', province: 'PH-PAN' },
  { name: 'Dagupan', province: 'PH-PAN' },
  { name: 'Dasol', province: 'PH-PAN' },
  { name: 'Infanta', province: 'PH-PAN' },
  { name: 'Labrador', province: 'PH-PAN' },
  { name: 'Laoac', province: 'PH-PAN' },
  { name: 'Lingayen', province: 'PH-PAN' },
  { name: 'Mabini', province: 'PH-PAN' },
  { name: 'Malasiqui', province: 'PH-PAN' },
  { name: 'Manaoag', province: 'PH-PAN' },
  { name: 'Mangaldan', province: 'PH-PAN' },
  { name: 'Mangatarem', province: 'PH-PAN' },
  { name: 'Mapandan', province: 'PH-PAN' },
  { name: 'Natividad', province: 'PH-PAN' },
  { name: 'Pozorrubio', province: 'PH-PAN' },
  { name: 'Rosales', province: 'PH-PAN' },
  { name: 'San Carlos', province: 'PH-PAN' },
  { name: 'San Fabian', province: 'PH-PAN' },
  { name: 'San Jacinto', province: 'PH-PAN' },
  { name: 'San Manuel', province: 'PH-PAN' },
  { name: 'San Nicolas', province: 'PH-PAN' },
  { name: 'San Quintin', province: 'PH-PAN' },
  { name: 'Santa Barbara', province: 'PH-PAN' },
  { name: 'Santa Maria', province: 'PH-PAN' },
  { name: 'Santo Tomas', province: 'PH-PAN' },
  { name: 'Sison', province: 'PH-PAN' },
  { name: 'Sual', province: 'PH-PAN' },
  { name: 'Tayug', province: 'PH-PAN' },
  { name: 'Umingan', province: 'PH-PAN' },
  { name: 'Urbiztondo', province: 'PH-PAN' },
  { name: 'Urdaneta', province: 'PH-PAN' },
  { name: 'Villasis', province: 'PH-PAN' },
  { name: 'Agdangan', province: 'PH-QUE' },
  { name: 'Alabat', province: 'PH-QUE' },
  { name: 'Atimonan', province: 'PH-QUE' },
  { name: 'Buenavista', province: 'PH-QUE' },
  { name: 'Burdeos', province: 'PH-QUE' },
  { name: 'Calauag', province: 'PH-QUE' },
  { name: 'Candelaria', province: 'PH-QUE' },
  { name: 'Catanauan', province: 'PH-QUE' },
  { name: 'Dolores', province: 'PH-QUE' },
  { name: 'General Luna', province: 'PH-QUE' },
  { name: 'General Nakar', province: 'PH-QUE' },
  { name: 'Guinayangan', province: 'PH-QUE' },
  { name: 'Gumaca', province: 'PH-QUE' },
  { name: 'Infanta', province: 'PH-QUE' },
  { name: 'Jomalig', province: 'PH-QUE' },
  { name: 'Lopez', province: 'PH-QUE' },
  { name: 'Lucban', province: 'PH-QUE' },
  { name: 'Lucena', province: 'PH-QUE' },
  { name: 'Macalelon', province: 'PH-QUE' },
  { name: 'Mauban', province: 'PH-QUE' },
  { name: 'Mulanay', province: 'PH-QUE' },
  { name: 'Padre Burgos', province: 'PH-QUE' },
  { name: 'Pagbilao', province: 'PH-QUE' },
  { name: 'Panukulan', province: 'PH-QUE' },
  { name: 'Patnanungan', province: 'PH-QUE' },
  { name: 'Perez', province: 'PH-QUE' },
  { name: 'Pitogo', province: 'PH-QUE' },
  { name: 'Plaridel', province: 'PH-QUE' },
  { name: 'Polillo', province: 'PH-QUE' },
  { name: 'Quezon', province: 'PH-QUE' },
  { name: 'Real', province: 'PH-QUE' },
  { name: 'Sampaloc', province: 'PH-QUE' },
  { name: 'San Andres', province: 'PH-QUE' },
  { name: 'San Antonio', province: 'PH-QUE' },
  { name: 'San Francisco (Aurora)', province: 'PH-QUE' },
  { name: 'San Narciso', province: 'PH-QUE' },
  { name: 'Sariaya', province: 'PH-QUE' },
  { name: 'Tagkawayan', province: 'PH-QUE' },
  { name: 'Tayabas', province: 'PH-QUE' },
  { name: 'Tiaong', province: 'PH-QUE' },
  { name: 'Unisan', province: 'PH-QUE' },
  { name: 'Aglipay', province: 'PH-QUI' },
  { name: 'Cabarroguis', province: 'PH-QUI' },
  { name: 'Diffun', province: 'PH-QUI' },
  { name: 'Maddela', province: 'PH-QUI' },
  { name: 'Nagtipunan', province: 'PH-QUI' },
  { name: 'Saguday', province: 'PH-QUI' },
  { name: 'Angono', province: 'PH-RIZ' },
  { name: 'Antipolo', province: 'PH-RIZ' },
  { name: 'Baras', province: 'PH-RIZ' },
  { name: 'Binangonan', province: 'PH-RIZ' },
  { name: 'Cainta', province: 'PH-RIZ' },
  { name: 'Cardona', province: 'PH-RIZ' },
  { name: 'Jalajala', province: 'PH-RIZ' },
  { name: 'Morong', province: 'PH-RIZ' },
  { name: 'Pililla', province: 'PH-RIZ' },
  { name: 'Rodriguez (Montalban)', province: 'PH-RIZ' },
  { name: 'San Mateo', province: 'PH-RIZ' },
  { name: 'Tanay', province: 'PH-RIZ' },
  { name: 'Taytay', province: 'PH-RIZ' },
  { name: 'Teresa', province: 'PH-RIZ' },
  { name: 'Alcantara', province: 'PH-ROM' },
  { name: 'Banton (Jones)', province: 'PH-ROM' },
  { name: 'Cajidiocan', province: 'PH-ROM' },
  { name: 'Calatrava', province: 'PH-ROM' },
  { name: 'Concepcion', province: 'PH-ROM' },
  { name: 'Corcuera', province: 'PH-ROM' },
  { name: 'Ferrol', province: 'PH-ROM' },
  { name: 'Looc', province: 'PH-ROM' },
  { name: 'Magdiwang', province: 'PH-ROM' },
  { name: 'Odiongan', province: 'PH-ROM' },
  { name: 'Romblon', province: 'PH-ROM' },
  { name: 'San Agustin', province: 'PH-ROM' },
  { name: 'San Andres', province: 'PH-ROM' },
  { name: 'San Fernando', province: 'PH-ROM' },
  { name: 'San Jose', province: 'PH-ROM' },
  { name: 'Santa Fe', province: 'PH-ROM' },
  { name: 'Santa Maria (Imelda)', province: 'PH-ROM' },
  { name: 'Almagro', province: 'PH-WSA' },
  { name: 'Basey', province: 'PH-WSA' },
  { name: 'Calbayog', province: 'PH-WSA' },
  { name: 'Calbiga', province: 'PH-WSA' },
  { name: 'Catbalogan', province: 'PH-WSA' },
  { name: 'Daram', province: 'PH-WSA' },
  { name: 'Gandara', province: 'PH-WSA' },
  { name: 'Hinabangan', province: 'PH-WSA' },
  { name: 'Jiabong', province: 'PH-WSA' },
  { name: 'Marabut', province: 'PH-WSA' },
  { name: 'Matuguinao', province: 'PH-WSA' },
  { name: 'Motiong', province: 'PH-WSA' },
  { name: 'Pagsanghan', province: 'PH-WSA' },
  { name: 'Paranas (Wright)', province: 'PH-WSA' },
  { name: 'Pinabacdao', province: 'PH-WSA' },
  { name: 'San Jorge', province: 'PH-WSA' },
  { name: 'San Jose de Buan', province: 'PH-WSA' },
  { name: 'San Sebastian', province: 'PH-WSA' },
  { name: 'Santa Margarita', province: 'PH-WSA' },
  { name: 'Santa Rita', province: 'PH-WSA' },
  { name: 'Santo Niño', province: 'PH-WSA' },
  { name: 'Tagapul-an', province: 'PH-WSA' },
  { name: 'Talalora', province: 'PH-WSA' },
  { name: 'Tarangnan', province: 'PH-WSA' },
  { name: 'Villareal', province: 'PH-WSA' },
  { name: 'Zumarraga', province: 'PH-WSA' },
  { name: 'Alabel', province: 'PH-SAR' },
  { name: 'Glan', province: 'PH-SAR' },
  { name: 'Kiamba', province: 'PH-SAR' },
  { name: 'Maasim', province: 'PH-SAR' },
  { name: 'Maitum', province: 'PH-SAR' },
  { name: 'Malapatan', province: 'PH-SAR' },
  { name: 'Malungon', province: 'PH-SAR' },
  { name: 'Enrique Villanueva', province: 'PH-SIG' },
  { name: 'Larena', province: 'PH-SIG' },
  { name: 'Lazi', province: 'PH-SIG' },
  { name: 'Maria', province: 'PH-SIG' },
  { name: 'San Juan', province: 'PH-SIG' },
  { name: 'Siquijor', province: 'PH-SIG' },
  { name: 'Barcelona', province: 'PH-SOR' },
  { name: 'Bulan', province: 'PH-SOR' },
  { name: 'Bulusan', province: 'PH-SOR' },
  { name: 'Casiguran', province: 'PH-SOR' },
  { name: 'Castilla', province: 'PH-SOR' },
  { name: 'Donsol', province: 'PH-SOR' },
  { name: 'Gubat', province: 'PH-SOR' },
  { name: 'Irosin', province: 'PH-SOR' },
  { name: 'Juban', province: 'PH-SOR' },
  { name: 'Magallanes', province: 'PH-SOR' },
  { name: 'Matnog', province: 'PH-SOR' },
  { name: 'Pilar', province: 'PH-SOR' },
  { name: 'Prieto Diaz', province: 'PH-SOR' },
  { name: 'Santa Magdalena', province: 'PH-SOR' },
  { name: 'Sorsogon City', province: 'PH-SOR' },
  { name: 'Banga', province: 'PH-SCO' },
  { name: 'General Santos (Dadiangas)', province: 'PH-SCO' },
  { name: 'Koronadal', province: 'PH-SCO' },
  { name: 'Lake Sebu', province: 'PH-SCO' },
  { name: 'Norala', province: 'PH-SCO' },
  { name: 'Polomolok', province: 'PH-SCO' },
  { name: 'Santo Niño', province: 'PH-SCO' },
  { name: 'Surallah', province: 'PH-SCO' },
  { name: 'T\'Boli', province: 'PH-SCO' },
  { name: 'Tampakan', province: 'PH-SCO' },
  { name: 'Tantangan', province: 'PH-SCO' },
  { name: 'Tupi', province: 'PH-SCO' },
  { name: 'Anahawan', province: 'PH-SLE' },
  { name: 'Bontoc', province: 'PH-SLE' },
  { name: 'Hinunangan', province: 'PH-SLE' },
  { name: 'Hinundayan', province: 'PH-SLE' },
  { name: 'Libagon', province: 'PH-SLE' },
  { name: 'Liloan', province: 'PH-SLE' },
  { name: 'Limasawa', province: 'PH-SLE' },
  { name: 'Maasin', province: 'PH-SLE' },
  { name: 'Macrohon', province: 'PH-SLE' },
  { name: 'Malitbog', province: 'PH-SLE' },
  { name: 'Padre Burgos', province: 'PH-SLE' },
  { name: 'Pintuyan', province: 'PH-SLE' },
  { name: 'Saint Bernard', province: 'PH-SLE' },
  { name: 'San Francisco', province: 'PH-SLE' },
  { name: 'San Juan (Cabalian)', province: 'PH-SLE' },
  { name: 'San Ricardo', province: 'PH-SLE' },
  { name: 'Silago', province: 'PH-SLE' },
  { name: 'Sogod', province: 'PH-SLE' },
  { name: 'Tomas Oppus', province: 'PH-SLE' },
  { name: 'Bagumbayan', province: 'PH-SUK' },
  { name: 'Columbio', province: 'PH-SUK' },
  { name: 'Esperanza', province: 'PH-SUK' },
  { name: 'Isulan', province: 'PH-SUK' },
  { name: 'Kalamansig', province: 'PH-SUK' },
  { name: 'Lambayong (Mariano Marcos)', province: 'PH-SUK' },
  { name: 'Lebak', province: 'PH-SUK' },
  { name: 'Lutayan', province: 'PH-SUK' },
  { name: 'Palimbang', province: 'PH-SUK' },
  { name: 'President Quirino', province: 'PH-SUK' },
  { name: 'Senator Ninoy Aquino', province: 'PH-SUK' },
  { name: 'Tacurong', province: 'PH-SUK' },
  { name: 'Banguingui (Tongkil)', province: 'PH-SLU' },
  { name: 'Hadji Panglima Tahil (Marunggas)', province: 'PH-SLU' },
  { name: 'Indanan', province: 'PH-SLU' },
  { name: 'Jolo', province: 'PH-SLU' },
  { name: 'Kalingalan Caluang', province: 'PH-SLU' },
  { name: 'Lugus', province: 'PH-SLU' },
  { name: 'Luuk', province: 'PH-SLU' },
  { name: 'Maimbung', province: 'PH-SLU' },
  { name: 'Old Panamao', province: 'PH-SLU' },
  { name: 'Omar', province: 'PH-SLU' },
  { name: 'Pandami', province: 'PH-SLU' },
  { name: 'Panglima Estino (New Panamao)', province: 'PH-SLU' },
  { name: 'Pangutaran', province: 'PH-SLU' },
  { name: 'Parang', province: 'PH-SLU' },
  { name: 'Pata', province: 'PH-SLU' },
  { name: 'Patikul', province: 'PH-SLU' },
  { name: 'Siasi', province: 'PH-SLU' },
  { name: 'Talipao', province: 'PH-SLU' },
  { name: 'Tapul', province: 'PH-SLU' },
  { name: 'Alegria', province: 'PH-SUN' },
  { name: 'Bacuag', province: 'PH-SUN' },
  { name: 'Burgos', province: 'PH-SUN' },
  { name: 'Claver', province: 'PH-SUN' },
  { name: 'Dapa', province: 'PH-SUN' },
  { name: 'Del Carmen', province: 'PH-SUN' },
  { name: 'General Luna', province: 'PH-SUN' },
  { name: 'Gigaquit', province: 'PH-SUN' },
  { name: 'Mainit', province: 'PH-SUN' },
  { name: 'Malimono', province: 'PH-SUN' },
  { name: 'Pilar', province: 'PH-SUN' },
  { name: 'Placer', province: 'PH-SUN' },
  { name: 'San Benito', province: 'PH-SUN' },
  { name: 'San Francisco (Anao-Aon)', province: 'PH-SUN' },
  { name: 'San Isidro', province: 'PH-SUN' },
  { name: 'Santa Monica (Sapao)', province: 'PH-SUN' },
  { name: 'Sison', province: 'PH-SUN' },
  { name: 'Socorro', province: 'PH-SUN' },
  { name: 'Surigao City', province: 'PH-SUN' },
  { name: 'Tagana-an', province: 'PH-SUN' },
  { name: 'Tubod', province: 'PH-SUN' },
  { name: 'Barobo', province: 'PH-SUR' },
  { name: 'Bayabas', province: 'PH-SUR' },
  { name: 'Bislig', province: 'PH-SUR' },
  { name: 'Cagwait', province: 'PH-SUR' },
  { name: 'Cantilan', province: 'PH-SUR' },
  { name: 'Carmen', province: 'PH-SUR' },
  { name: 'Carrascal', province: 'PH-SUR' },
  { name: 'Cortes', province: 'PH-SUR' },
  { name: 'Hinatuan', province: 'PH-SUR' },
  { name: 'Lanuza', province: 'PH-SUR' },
  { name: 'Lianga', province: 'PH-SUR' },
  { name: 'Lingig', province: 'PH-SUR' },
  { name: 'Madrid', province: 'PH-SUR' },
  { name: 'Marihatag', province: 'PH-SUR' },
  { name: 'San Agustin', province: 'PH-SUR' },
  { name: 'San Miguel', province: 'PH-SUR' },
  { name: 'Tagbina', province: 'PH-SUR' },
  { name: 'Tago', province: 'PH-SUR' },
  { name: 'Tandag', province: 'PH-SUR' },
  { name: 'Anao', province: 'PH-TAR' },
  { name: 'Bamban', province: 'PH-TAR' },
  { name: 'Camiling', province: 'PH-TAR' },
  { name: 'Capas', province: 'PH-TAR' },
  { name: 'Concepcion', province: 'PH-TAR' },
  { name: 'Gerona', province: 'PH-TAR' },
  { name: 'La Paz', province: 'PH-TAR' },
  { name: 'Mayantoc', province: 'PH-TAR' },
  { name: 'Moncada', province: 'PH-TAR' },
  { name: 'Paniqui', province: 'PH-TAR' },
  { name: 'Pura', province: 'PH-TAR' },
  { name: 'Ramos', province: 'PH-TAR' },
  { name: 'San Clemente', province: 'PH-TAR' },
  { name: 'San Jose', province: 'PH-TAR' },
  { name: 'San Manuel', province: 'PH-TAR' },
  { name: 'Santa Ignacia', province: 'PH-TAR' },
  { name: 'Tarlac City', province: 'PH-TAR' },
  { name: 'Victoria', province: 'PH-TAR' },
  { name: 'Bongao', province: 'PH-TAW' },
  { name: 'Languyan', province: 'PH-TAW' },
  { name: 'Mapun (Cagayan de Tawi-Tawi)', province: 'PH-TAW' },
  { name: 'Panglima Sugala (Balimbing)', province: 'PH-TAW' },
  { name: 'Sapa-Sapa', province: 'PH-TAW' },
  { name: 'Sibutu', province: 'PH-TAW' },
  { name: 'Simunul', province: 'PH-TAW' },
  { name: 'Sitangkai', province: 'PH-TAW' },
  { name: 'South Ubian', province: 'PH-TAW' },
  { name: 'Tandubas', province: 'PH-TAW' },
  { name: 'Turtle Islands (Taganak)', province: 'PH-TAW' },
  { name: 'Botolan', province: 'PH-ZMB' },
  { name: 'Cabangan', province: 'PH-ZMB' },
  { name: 'Candelaria', province: 'PH-ZMB' },
  { name: 'Castillejos', province: 'PH-ZMB' },
  { name: 'Iba', province: 'PH-ZMB' },
  { name: 'Masinloc', province: 'PH-ZMB' },
  { name: 'Olongapo', province: 'PH-ZMB' },
  { name: 'Palauig', province: 'PH-ZMB' },
  { name: 'San Antonio', province: 'PH-ZMB' },
  { name: 'San Felipe', province: 'PH-ZMB' },
  { name: 'San Marcelino', province: 'PH-ZMB' },
  { name: 'San Narciso', province: 'PH-ZMB' },
  { name: 'Santa Cruz', province: 'PH-ZMB' },
  { name: 'Subic', province: 'PH-ZMB' },
  { name: 'Baliguian', province: 'PH-ZAN' },
  { name: 'Dapitan', province: 'PH-ZAN' },
  { name: 'Dipolog', province: 'PH-ZAN' },
  { name: 'Godod', province: 'PH-ZAN' },
  { name: 'Gutalac', province: 'PH-ZAN' },
  { name: 'Jose Dalman (Ponot)', province: 'PH-ZAN' },
  { name: 'Kalawit', province: 'PH-ZAN' },
  { name: 'Katipunan', province: 'PH-ZAN' },
  { name: 'La Libertad', province: 'PH-ZAN' },
  { name: 'Labason', province: 'PH-ZAN' },
  { name: 'Leon B. Postigo (Bacungan)', province: 'PH-ZAN' },
  { name: 'Liloy', province: 'PH-ZAN' },
  { name: 'Manukan', province: 'PH-ZAN' },
  { name: 'Mutia', province: 'PH-ZAN' },
  { name: 'Piñan (New Piñan)', province: 'PH-ZAN' },
  { name: 'Polanco', province: 'PH-ZAN' },
  { name: 'President Manuel A. Roxas', province: 'PH-ZAN' },
  { name: 'Rizal', province: 'PH-ZAN' },
  { name: 'Salug', province: 'PH-ZAN' },
  { name: 'Sergio Osmeña Sr.', province: 'PH-ZAN' },
  { name: 'Siayan', province: 'PH-ZAN' },
  { name: 'Sibuco', province: 'PH-ZAN' },
  { name: 'Sibutad', province: 'PH-ZAN' },
  { name: 'Sindangan', province: 'PH-ZAN' },
  { name: 'Siocon', province: 'PH-ZAN' },
  { name: 'Sirawai', province: 'PH-ZAN' },
  { name: 'Tampilisan', province: 'PH-ZAN' },
  { name: 'Aurora', province: 'PH-ZAS' },
  { name: 'Bayog', province: 'PH-ZAS' },
  { name: 'Dimataling', province: 'PH-ZAS' },
  { name: 'Dinas', province: 'PH-ZAS' },
  { name: 'Dumalinao', province: 'PH-ZAS' },
  { name: 'Dumingag', province: 'PH-ZAS' },
  { name: 'Guipos', province: 'PH-ZAS' },
  { name: 'Josefina', province: 'PH-ZAS' },
  { name: 'Kumalarang', province: 'PH-ZAS' },
  { name: 'Labangan', province: 'PH-ZAS' },
  { name: 'Lakewood', province: 'PH-ZAS' },
  { name: 'Lapuyan', province: 'PH-ZAS' },
  { name: 'Mahayag', province: 'PH-ZAS' },
  { name: 'Margosatubig', province: 'PH-ZAS' },
  { name: 'Midsalip', province: 'PH-ZAS' },
  { name: 'Molave', province: 'PH-ZAS' },
  { name: 'Pagadian', province: 'PH-ZAS' },
  { name: 'Pitogo', province: 'PH-ZAS' },
  { name: 'Ramon Magsaysay (Liargo)', province: 'PH-ZAS' },
  { name: 'San Miguel', province: 'PH-ZAS' },
  { name: 'San Pablo', province: 'PH-ZAS' },
  { name: 'Sominot (Don Mariano Marcos)', province: 'PH-ZAS' },
  { name: 'Tabina', province: 'PH-ZAS' },
  { name: 'Tambulig', province: 'PH-ZAS' },
  { name: 'Tigbao', province: 'PH-ZAS' },
  { name: 'Tukuran', province: 'PH-ZAS' },
  { name: 'Vincenzo A. Sagun', province: 'PH-ZAS' },
  { name: 'Zamboanga City', province: 'PH-ZAS' },
  { name: 'Alicia', province: 'PH-ZSI' },
  { name: 'Buug', province: 'PH-ZSI' },
  { name: 'Diplahan', province: 'PH-ZSI' },
  { name: 'Imelda', province: 'PH-ZSI' },
  { name: 'Ipil', province: 'PH-ZSI' },
  { name: 'Kabasalan', province: 'PH-ZSI' },
  { name: 'Mabuhay', province: 'PH-ZSI' },
  { name: 'Malangas', province: 'PH-ZSI' },
  { name: 'Naga', province: 'PH-ZSI' },
  { name: 'Olutanga', province: 'PH-ZSI' },
  { name: 'Payao', province: 'PH-ZSI' },
  { name: 'Roseller Lim', province: 'PH-ZSI' },
  { name: 'Siay', province: 'PH-ZSI' },
  { name: 'Talusan', province: 'PH-ZSI' },
  { name: 'Titay', province: 'PH-ZSI' },
  { name: 'Tungawan', province: 'PH-ZSI' },
]